### ISSUE TITLE
Color seems to differ from GTK theme

### ISSUE THREAD

**Issue by gabrc52** [PapirusDevelopmentTeam/materia-kde#1]
This issue can be seen from this screenshot: https://i.imgur.com/wvwX3OG.png

**Comment by ArchangeGabriel** [comment]
@gabrc52 Aren’t you using Adapta rather than Materia? This looks like Adapta colors.

**Comment by gabrc52** [comment]
After installing the official version of the GTK theme, the color looks like the screenshot in nana-4/materia-theme, so the issue is with the GTK theme in the AUR (https://github.com/nana-4/materia-theme)

**Comment by ArchangeGabriel** [comment]
I’ll look into fixing the AUR package and moving it into [community].
