### ISSUE TITLE
Incomplete Uninstallation

### ISSUE THREAD

**Issue by 2shrestha22** [PapirusDevelopmentTeam/materia-kde#100]
When uninstalling materia-kde with `wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/materia-kde/master/install.sh | uninstall=true sh` plasma style and desktop style are left behind.
I had to manually remove materia related folders from `/usr/plasma/desktoptheme` and `~/.local/share/aurorae/themes/`
.

**Comment by varlesh** [comment]
you can remove all Materia's Themes with make option
```
git clone https://github.com/PapirusDevelopmentTeam/materia-kde.git
cd materia-kde
sudo make uninstall
```
about `~/.local/share/` if you install this from KDE Browser, you can delete that from KDE Browser
