### ISSUE TITLE
Support Plasma 5.21 margin separators

### ISSUE THREAD

**Issue by SuNNjek** [PapirusDevelopmentTeam/materia-kde#101]
Plasma 5.21 introduces margin separator widgets which need support from the theme. For more information see [this video](https://www.youtube.com/watch?v=99RPMVzipls) by one of the KDE devs. It would be awesome if this would be supported by this theme.

**Comment by varlesh** [comment]
Will be added, when Plasma 5.21 released

**Comment by varlesh** [comment]
@SuNNjek This used only on panel?

**Comment by SuNNjek** [comment]
@varlesh I think so but I don't know exactly, sorry
