### ISSUE TITLE
Show user icon beside name

### ISSUE THREAD

**Issue by huntantr** [PapirusDevelopmentTeam/materia-kde#102]
Show the users profile icon beside their name in the SDDM theme.

**Comment by varlesh** [comment]
added:
![screenshot](https://user-images.githubusercontent.com/8083855/107139300-9771d380-6933-11eb-8edf-331a9a07c6e1.png)
![image](https://user-images.githubusercontent.com/8083855/107139341-e0298c80-6933-11eb-8e9a-cdbb5dbc16e1.png)
place for your avatar `~/.face.icon`
