### ISSUE TITLE
Huge borders for Materia Dark window decoration

### ISSUE THREAD

**Issue by Dkoeddnsnp** [PapirusDevelopmentTeam/materia-kde#104]
![MateriaDark](https://user-images.githubusercontent.com/66845002/107144693-8fbb2a80-6945-11eb-9c41-5ea354e7f571.png)
There are a huge borders when applying dark decoration. No such issues with light decoration
![Matreia light](https://user-images.githubusercontent.com/66845002/107144746-e88ac300-6945-11eb-8c28-643cd944fa45.png)
.

**Comment by varlesh** [comment]
not confirm this. Try remove cache `rm -rf ~/.cache/plasm*`
and restart KWin: `killall -9 kwin_x11`
**ALT + F2** > _kwin_x11_ > **Enter**

**Comment by Dkoeddnsnp** [comment]
That works.

**Comment by AlvinZhu** [comment]
> not confirm this. Try remove cache `rm -rf ~/.cache/plasm*`
> and restart KWin: `killall -9 kwin_x11`
> **ALT + F2** > `kwin_x11` > **Enter**

Huge borders for Materia, Materia Dark and Materia Light.
remove cache and restart KWin not work

**Comment by varlesh** [comment]
@AlvinZhu You install theme only on home folder? Please check maybe it's duplicate on root folder too...
```
~/.local/share/aurorae/themes/
/usr/share/aurorae/themes/
```

**Comment by AlvinZhu** [comment]
> @AlvinZhu You install theme only on home folder? Please check maybe it's duplicate on root folder too...
> 
> ```
> ~/.local/share/aurorae/themes/
> /usr/share/aurorae/themes/
> ```

I install this theme from archlinux package repository.
![Screenshot_20210221_122626](https://user-images.githubusercontent.com/4264000/108615542-1ee53980-7440-11eb-99ed-aaae25239984.png)
![Screenshot_20210221_122635](https://user-images.githubusercontent.com/4264000/108615543-21e02a00-7440-11eb-8aba-759736b9500b.png)

**Comment by varlesh** [comment]
@AlvinZhu It's not huge borders, it's normal borders. Set **No Borders** on Decoration settings (see cursor screen)
![image](https://user-images.githubusercontent.com/8083855/108615585-20ead080-741f-11eb-951f-287bce18b464.png)

**Comment by AlvinZhu** [comment]
version: 20210217:
![Screenshot_20210221_123200](https://user-images.githubusercontent.com/4264000/108615600-d5491e80-7440-11eb-946c-30fd77806436.png)

I install the old version of Materia-KDE
version 20201222:
![Screenshot_20210221_123403](https://user-images.githubusercontent.com/4264000/108615630-193c2380-7441-11eb-8b52-3d1e715d7f23.png)

I prefer this version

**Comment by varlesh** [comment]
@AlvinZhu you have Nvidia card?

**Comment by varlesh** [comment]
See instructions, how fix that:
https://github.com/PapirusDevelopmentTeam/materia-kde#known-issues
https://bugs.kde.org/show_bug.cgi?id=384457
https://forums.developer.nvidia.com/t/kde-wrong-render-buttons-aurorae-decoration-on-nvidia/53255

**Comment by AlvinZhu** [comment]
@varlesh 
Yes. I installed the NVIDIA Driver. 
I have a thunderbolt eGPU.  not plug in.
I use Intel GPU only now.

**Comment by varlesh** [comment]
it's strange... for intel. hm. Earlier i'm use opensource drivers and all rendered fine

**Comment by varlesh** [comment]
How to determine this?
See on buttons. When DPI settings not applied - decoration have wrong rendering:
![image](https://user-images.githubusercontent.com/8083855/108615884-eb93b200-7421-11eb-83ef-24468a76b031.png)

**Comment by varlesh** [comment]
after fix DPI & restart PC now all fine:
![image](https://user-images.githubusercontent.com/8083855/108615936-4927fe80-7422-11eb-9408-f409e3406727.png)

**Comment by varlesh** [comment]
**~/.Xresources**
```
Xft.dpi:       96
Xft.antialias: true
Xft.hinting:   true
Xft.autohint:  false
Xft.hintstyle: hintslight
Xft.lcdfilter: lcddefault
Xft.rgba:      rgb
```
@AlvinZhu It's solved your problem?

**Comment by AlvinZhu** [comment]
@varlesh 
Thanks, I found the problem.
Yes. It’s the DPI setting.
I set "Force font DPI" to 108
I need to set it to 96. so the theme looks fine.
Can this theme support different DPI?

**Comment by varlesh** [comment]
I don't know)) Aurorae very old engine, need test it

**Comment by varlesh** [comment]
@Dkoeddnsnp You have too wrong rendering. See your screen:
![image](https://user-images.githubusercontent.com/8083855/108616111-036c3580-7424-11eb-9aee-5cc0c63039a2.png)

**Comment by varlesh** [comment]
It's very old Nvidia bug. I don't know why don't want fix that
