### ISSUE TITLE
SDDM Theme cant choose desktop schemas properly

### ISSUE THREAD

**Issue by Chalkim** [PapirusDevelopmentTeam/materia-kde#105]
### Brief description of bug
SDDM Theme (both light and dark version) cant choose desktop schemas. No matter which I choose, it always runs into the first desktop schemas.

#### Environment(for bug reports)
Operating System: Arch Linux
KDE Plasma Version: 5.21.0
KDE Frameworks Version: 5.79.0
Qt Version: 5.15.2
Kernel Version: 5.10.16-arch1-1
OS Type: 64-bit
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-7300HQ CPU @ 2.50GHz
Memory: 7.5 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 630

#### My configuration
First I only installed KDE, everything is OK. Then I installed i3wm, something wrong happened. Even I have chosen Plasma, SDDM runs into i3wm. I have to adjust SDDM config so I can load KDE. I have tried other different SDDM theme, and all behave properly. So I think it's maybe a bug.
![Screenshot_20210218_150820](https://user-images.githubusercontent.com/37498010/108318771-544d1580-71fb-11eb-9952-ebe64ad4cee5.png)
Sorry for not providing screenshot of SDDM. I dont know how to capture a screenshot in SDDM.

**Comment by varlesh** [comment]
Thx for report bug. It's will be fixed now.
Note: This SDDM themes not need plasma desktop for work ))

**Comment by varlesh** [comment]
Please test it with latest git master branch

**Comment by varlesh** [comment]
@Chalkim Also all Materia's Aurorae themes support **No Borders** option on last release

**Comment by Chalkim** [comment]
Great! Now I can get into both i3wm and KDE. Thx a lot!
