### ISSUE TITLE
Hovering top right button when maximized

### ISSUE THREAD

**Issue by lucasjome** [PapirusDevelopmentTeam/materia-kde#107]
When a window is maximized, I can't hover over the close button if I move the mouse cursor to the top corner of the screen.
But with Breeze's window decoration, it's possible and also super useful.

It's somehow a bug or the intended way of working?

**Comment by varlesh** [comment]
This implemented as GTK version 4px offset button from up & right.
GTK:
![Screenshot_20210316_081017-1](https://user-images.githubusercontent.com/8083855/111255025-b6007400-862f-11eb-82a5-222c60ba5897.png)
Qt:
![Screenshot_20210316_081052-1](https://user-images.githubusercontent.com/8083855/111255057-c9abda80-862f-11eb-94e0-231aa2da687b.png)

**Comment by varlesh** [comment]
You can use custom settings for buttons on rc-file.
For example set 0 px offset on **Materia-Darkrc**:
```
TitleEdgeTopMaximized=0
TitleEdgeLeftMaximized=0
TitleEdgeRightMaximized=0
```
Restart KWin:
`killall -9 kwin_x11`
Run KWin on Krunner **ALT+F2**
`kwin_x11`

Result:
![image](https://user-images.githubusercontent.com/8083855/111256849-6cb22380-8633-11eb-9098-a11c93c6b1bd.png)
