### ISSUE TITLE
New Session button in Yakuake is small

### ISSUE THREAD

**Issue by StarFleetCPTN** [PapirusDevelopmentTeam/materia-kde#108]
The new session button on the Yakuake dropdown is small and it leaves blank spaces on each side of the button.

![2021-03-16_09-57](https://user-images.githubusercontent.com/2897199/111349311-43e35b80-863e-11eb-99c3-3f8866fbc5c2.png)

Software Versions:
community/materia-kde 20210307-1
extra/yakuake 20.12.3-1
community/papirus-icon-theme 20210302-1

![2021-03-16_10-05](https://user-images.githubusercontent.com/2897199/111350331-3bd7eb80-863f-11eb-875b-4de392c4bf87.png)

**Comment by varlesh** [comment]
It's upstream bug, because previous Yakuake version worked fine with SVG.
I'm convert SVG's to PNG's. Try it

**Comment by varlesh** [comment]
Bug reported:
https://bugs.kde.org/show_bug.cgi?id=434525
