### ISSUE TITLE
[feature request] a change_colors script

### ISSUE THREAD

**Issue by lelgenio** [PapirusDevelopmentTeam/materia-kde#109]
[Similar to this](https://github.com/nana-4/materia-theme/blob/master/change_color.sh)

Just using `sed s/.../.../g -i */*` works, the problem is knowing what exact color is used for each element and dealing with changes in the default color scheme.    
Using the same input format as the one on the gtk side of things would be useful.

I would be willing to contribute if necessary ;)

**Comment by lelgenio** [comment]
also, i have seen https://github.com/PapirusDevelopmentTeam/materia-kde/issues/23 and agree with keeping a single suported theme. this would be just a convinience for hacking around.

**Comment by varlesh** [comment]
It's pointless, because you broken plasma color schemes, also plasma color schemes not support alpha-channel.
![image](https://user-images.githubusercontent.com/8083855/112709414-d7384e80-8ed2-11eb-8f72-6e551ebad024.png)

**Comment by lelgenio** [comment]
Ah, i see. the choice of naming this materia-**kde** is precise.     
I was under the impression this was a 1 to 1 Qt port of the Gtk materia-theme, sorry.
