### ISSUE TITLE
Windows decorations. Tiny buttons size don't change titlebar size

### ISSUE THREAD

**Issue by eugeneBecker** [PapirusDevelopmentTeam/materia-kde#110]
![screenshot](https://user-images.githubusercontent.com/21080116/112713213-2ab39800-8ee5-11eb-9925-2b0474eebfcd.jpg)

**Comment by varlesh** [comment]
hm, it's very interested. I think Kwin locked minimal Height Title size with read from config rc-file
By default it's 20px.
https://github.com/KDE/kwin/blob/master/src/plugins/kdecorations/aurorae/src/lib/themeconfig.h#L264
But check Button Size Factor:
https://github.com/KDE/kwin/blob/master/src/plugins/kdecorations/aurorae/src/qml/aurorae.qml#L152
And we have similar size on Buttons & Title - this minimal size...
https://github.com/PapirusDevelopmentTeam/materia-kde/blob/master/aurorae/themes/Materia/Materiarc#L43
https://github.com/PapirusDevelopmentTeam/materia-kde/blob/master/aurorae/themes/Materia/Materiarc#L24

**Comment by varlesh** [comment]
if **TitleHeight** = 21px or more, for example 40px  - minimal TitleHeight size will be 21px or 40px.

**Comment by eugeneBecker** [comment]
Do you have same issue? Maybe something with kwinrc?

**Comment by varlesh** [comment]
No, with Kwin all fine. 20px - it's minimal heght size for aurorae title. When if we use 21px or more - this will be minimal size for title height.
But we use 24px buttons & title too... it's more 20px and minimal size for title.
I can set  20px for title height, but need test it. And this broken my mind )))

**Comment by eugeneBecker** [comment]
I set TitleHeight=18 look fine. Except for buttons. They are blurred

**Comment by varlesh** [comment]
Yes, it's will be blurred, because we use 24px buttons size - it's normal title size.

**Comment by varlesh** [comment]
aurorae not support different button sizes

**Comment by varlesh** [comment]
@eugeneBecker You can set extra small title & buttons - set:
```
TitleHeight=12
ButtonHeight=12
ButtonWidth=12
```
On settings set normal button size

**Comment by varlesh** [comment]
result
![image](https://user-images.githubusercontent.com/8083855/112718312-9577ca00-8f0b-11eb-8c17-0ec1910285be.png)

**Comment by eugeneBecker** [comment]
Very small for 1080. But I will try to find the value I want

**Comment by varlesh** [comment]
original Materia GTK decoration use 32px Button size ))

**Comment by eugeneBecker** [comment]
I now. This takes more space. That's why i love KDE.

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/112718476-b55bbd80-8f0c-11eb-85c9-329d5420d42f.png)

**Comment by varlesh** [comment]
> Very small for 1080. But I will try to find the value I want

It's impossible. Icons will be blurred

**Comment by eugeneBecker** [comment]
So. I find this values. Looks good
TitleHeight=12
ButtonHeight=24
ButtonWidth=24

**Comment by varlesh** [comment]
It's only support minimal title size, but icons blurred

**Comment by eugeneBecker** [comment]
Heres screenshots
![2](https://user-images.githubusercontent.com/21080116/112718721-e8e71980-8f05-11eb-9137-94bca7a8684e.png)
![12px](https://user-images.githubusercontent.com/21080116/112718728-f13f5480-8f05-11eb-9d8b-611f7462f2ef.png)

**Comment by varlesh** [comment]
blurred:
![image](https://user-images.githubusercontent.com/8083855/112718778-95c59480-8f0e-11eb-8aa6-095e0042e903.png)

**Comment by eugeneBecker** [comment]
I don't understand how it works. But as I remember it was the same on previous versions. But thanks anyway. I don't think I could find these values :-)

**Comment by varlesh** [comment]
https://github.com/KDE/kwin/blob/master/src/plugins/kdecorations/aurorae/src/lib/auroraetheme.cpp#L473-L490

**Comment by varlesh** [comment]
i'm set 12px... but it\s solved only title size, buttons will be NON blurred only on Normal & Oversized

**Comment by eugeneBecker** [comment]
> i'm set 12px... but it\s solved only title size, buttons will be NON blurred only on Normal & Oversized

On normal and Oversized buttons looks clear even with my values

**Comment by varlesh** [comment]
With previous too))

**Comment by eugeneBecker** [comment]
We need an expert from the KDE project to explain how it works)

**Comment by varlesh** [comment]
https://github.com/KDE/kwin/blob/master/src/plugins/kdecorations/aurorae/src/lib/auroraetheme.cpp#L473-L490
Normal - 24px
Oversized - 48px
Tiny - 0.80% 24px  = 19,2px
Large - 1.2% 24px = 28,8px
VeryLarge - 1.4% 24px = 33,6px
and etc...
non round values will be blurred always

**Comment by eugeneBecker** [comment]
TitleHeight=18
ButtonHeight=24
ButtonWidth=24

This is not blurred so much, title size good

**Comment by eugeneBecker** [comment]
> https://github.com/KDE/kwin/blob/master/src/plugins/kdecorations/aurorae/src/lib/auroraetheme.cpp#L473-L490
> Normal 1% 24px = 24px
> Oversized 2% 24px = 48px
> Tiny - 0.80% 24px = 19,2px
> Large - 1.2% 24px = 28,8px
> VeryLarge - 1.4% 24px = 33,6px
> and etc...
> non round values will be blurred always

Yes. its true.

**Comment by varlesh** [comment]
it does not matter, because minimal title height size - it's button size = 24px.
If button size will be 22px, Tiny Title Height will be 17,6px
If button size will be 20px, Tiny Title Height will be 25px - it's round values, but wiil be blurred anyway, pixel grid will be broken.

12-24-48-72-96 = only this sizes will be have perfect pixel align

**Comment by varlesh** [comment]
if Tiny buttonSizeFactor will be - 0.5% we solved this problem and have 3 perfect pixel align

**Comment by eugeneBecker** [comment]
Actually, the blur is not that noticeable so much. The main thing we fixed title bar size

**Comment by varlesh** [comment]
@zzag Maybe better change step from 2 to 5? It's will be  have more rounded values and perfect pixel align
```
qreal AuroraeTheme::buttonSizeFactor() const
{
    switch (d->buttonSize) {
    case KDecoration2::BorderSize::Tiny:
        return 0.5;
    case KDecoration2::BorderSize::Large:
        return 1.5;
    case KDecoration2::BorderSize::VeryLarge:
        return 2.0;
    case KDecoration2::BorderSize::Huge:
        return 2.5;
    case KDecoration2::BorderSize::VeryHuge:
        return 3.0;
    case KDecoration2::BorderSize::Oversized:
        return 3.5;
    case KDecoration2::BorderSize::Normal: // fall through
    default:
        return 1.0;
    }
}
```

**Comment by eugeneBecker** [comment]
But this is required kwin patch, right?

**Comment by varlesh** [comment]
yes

**Comment by zzag** [comment]
It's tricky. We definitely cannot do that in Plasma 5 time frame because that will potentially break other window decoration themes.

**Comment by varlesh** [comment]
Why it's broken other themes? Normal size not changed - it's 1%. But we have more rounded values with this:
 - Tiny
 - Normal
 - Huge
 - VeryHuge

**Comment by eugeneBecker** [comment]
What about icons size? Is changing icons size fix this issue?

**Comment by varlesh** [comment]
@eugeneBecker for normal and oversized only

**Comment by eugeneBecker** [comment]
If icons had 25 px? insted 24.

Normal 1% 25px = 25px
Oversized 2% 25px = 50px
Tiny - 0.80% 25px = 20px
Large - 1.2% 25px = 30px
VeryLarge - 1.4% 24px = 35px

**Comment by varlesh** [comment]
No, it's broken pixel grid

**Comment by varlesh** [comment]
pixel perfect for 25px=25-50-75-100 and etc

**Comment by eugeneBecker** [comment]
Got it. Anyway thanks for help. Today i've learned more)
