### ISSUE TITLE
[kvantum] non uniform look with gtk materia light

### ISSUE THREAD

**Issue by AKorezin** [PapirusDevelopmentTeam/materia-kde#112]
## Summary
Window colors of materia-light kvantum and materia gtk differs.

## Expected behavior
Windows should have identical color for
1. window background
2. window menu
3. focus and unfocused states

## Screenshots
1. GTK reference
    ![image](https://user-images.githubusercontent.com/5399964/114033986-73c10000-9886-11eb-995a-1298a545ff47.png)
1. Kvantum Preview
    ![image](https://user-images.githubusercontent.com/5399964/114034763-26915e00-9887-11eb-9a26-1631e6cd52ac.png)

## Additional context
I think that some part of problem can be solved by disabling https://github.com/PapirusDevelopmentTeam/materia-kde/blob/5e64cf28ec22eab92ad751a24eb7ec7477b6c981/Kvantum/Materia/Materia.kvconfig#L586
But this option also requires to fix `window.color` so i've failed, because of different color in unfocused state.

**Comment by varlesh** [comment]
I'm not confirm this:
![image](https://user-images.githubusercontent.com/8083855/114164104-f8ba2100-993b-11eb-9f26-49b8fdefa522.png)
Maybe you use old aurorae theme?

**Comment by varlesh** [comment]
hm... i see light version update colors:
https://github.com/nana-4/materia-theme/blob/master/CHANGELOG.md
