### ISSUE TITLE
Question: LineEdit height

### ISSUE THREAD

**Issue by AKorezin** [PapirusDevelopmentTeam/materia-kde#114]
## Summary
After upgrade keepassxc from 2.6.2 to 2.6.3 or 2.6.4 I've found an issue reported it keepassxreboot/keepassxc#5984.
I think the problem is caused by keepassxreboot/keepassxc#5788.

## Question
Is this problem occurred because of keepassxc so it should be fixed there?
Could you please suggest any possible solutions for the issue?

**Comment by varlesh** [comment]
We can't doing anything! Widgets draw for all apps & we not have solution for single apps.
This LineEdit use custom style. Similar problem on qBittorent too:
![image](https://user-images.githubusercontent.com/8083855/114583772-f8e75300-9c92-11eb-9d2a-883c0db1d2d7.png)
