### ISSUE TITLE
Theme not available, debian 10 with materia from backports

### ISSUE THREAD

**Issue by gitlerat** [PapirusDevelopmentTeam/materia-kde#115]
Hi, 
I am running a fresh debian stable install with openbox as the only WM.

I Installed qt5ct and added this line in my .bash_profile: "QT_QPA_PLATFORMTHEME=qt5ct"

I installed materia-kde from buster-backports

If I launch qt5ct to change the plasma theme, materia is not available in the theme list.

Do I am missing something?

**Comment by varlesh** [comment]
`export QT_STYLE_OVERRIDE=kvantum`
More info here:
https://github.com/tsujan/Kvantum/issues/221

**Comment by gitlerat** [comment]
Thank you! I added the line in my .bash_profile and tried entering it in my terminal with " QT_STYLE_OVERRIDE=kvantum".

But If I launch qt5ct nothing changed...

**Comment by varlesh** [comment]
Theme selected on Kvantum Manager. On qt5ct - set kvantum engine

**Comment by varlesh** [comment]
qtct - it's Qt Configuration Tool, it's not engine and can use GTK2-style, Kvantum and etc on Qt-apps
Kvantum - it's SVG-based engine with theme support

**Comment by varlesh** [comment]
```
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_STYLE_OVERRIDE=kvantum
```
run qt5ct and apply Kvantum
run Kvantum Manager and apply Materia's theme
or set on `~/.config/Kvantum/kvantum.kvconfig`:
```
[General]
theme=MateriaDark
```

**Comment by gitlerat** [comment]
I Love you! Its working :)
