### ISSUE TITLE
System tray items not centered when using vertical panel, Plasma 5.22

### ISSUE THREAD

**Issue by jpenala** [PapirusDevelopmentTeam/materia-kde#116]
The latest Plasma Desktop (5.22) apparently added some padding around system tray items (at least the widget icons are now padded and smaller), and when using Materia KDE theme (installed with the Materia KDE Installer), the items are not centered anymore if one uses vertical panel.

Breeze
![breeze](https://user-images.githubusercontent.com/59263827/121768334-6b2ac580-cb66-11eb-9e95-ac6ff749ec74.png)

Materia
![materia](https://user-images.githubusercontent.com/59263827/121768345-7251d380-cb66-11eb-9ffc-dc168828b2f6.png)

**Comment by varlesh** [comment]
Thx for report, fixed

**Comment by jpenala** [comment]
Thank you for the quick fix!
