### ISSUE TITLE
Text overlap in certain text inputs

### ISSUE THREAD

**Issue by dchijk** [PapirusDevelopmentTeam/materia-kde#118]
This isn't happening with for example KvantumAdaptaBreathDark and also using Breeze application style. Also happening in apps like Kid3.

Materia Dark in custom shortcuts settings:
![image](https://user-images.githubusercontent.com/86939229/124411059-61cdec80-dd11-11eb-8a74-cbf9299da23c.png)

On other type of text input:
![image](https://user-images.githubusercontent.com/86939229/124411067-67c3cd80-dd11-11eb-9d56-7d630f090fe8.png)

With KvantumAdaptaBreathDark (and what should be like):
![image](https://user-images.githubusercontent.com/86939229/124411079-701c0880-dd11-11eb-873e-e9026cf0a822.png)

**Comment by varlesh** [comment]
fixed
