### ISSUE TITLE
Inactive tray icons on panels barely visible

### ISSUE THREAD

**Issue by atlas-ark** [PapirusDevelopmentTeam/materia-kde#119]
Materia Color Plasma Style + Materia Light Color scheme, theme applied using kvantum engine, Papirus Icons installed (Papirus Light selected).

![image](https://user-images.githubusercontent.com/37074205/124667346-924b8d00-deaf-11eb-928b-7692710edb87.png)

Volume icon in tray is almost not visible when muted.

Also the speaker icon in the volume menu:

![image](https://user-images.githubusercontent.com/37074205/124667626-f2423380-deaf-11eb-9727-9b2ce81e792c.png)

It could be that I'm not setting up the theme correctly, but I would have a completely white theme (not only windows, but also panels) with (obviously) darker icons.

Another thing with Materia Color theme is that "switches" are not colored properly:
![image](https://user-images.githubusercontent.com/37074205/124668059-9d52ed00-deb0-11eb-9da8-b891e7e8f3b8.png)

While in Breeze Light theme:
![image](https://user-images.githubusercontent.com/37074205/124668189-c83d4100-deb0-11eb-8de2-349b1136f7f8.png)

Thanks in advance!

**Comment by varlesh** [comment]
Thx for report, muted icon fixed.
About Switch widget... initially Latte draw switch as button, but now on Git-version support custom switch style. 
More info here:
https://invent.kde.org/plasma/latte-dock/-/issues/58
You can fix that, for example on KDE Neon:
`sudo wget https://invent.kde.org/plasma/latte-dock/-/raw/master/declarativeimports/components/private/SwitchStyle.qml -O /usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/latte/components/private/SwitchStyle.qml`

**Comment by varlesh** [comment]
and you give this:
![image](https://user-images.githubusercontent.com/8083855/124677198-f3378d00-ded0-11eb-88be-a75fca335f39.png)
