### ISSUE TITLE
Screenlocking not working on Kubuntu 20.04.2

### ISSUE THREAD

**Issue by oltemo93** [PapirusDevelopmentTeam/materia-kde#120]
I've installed the Materia KDE theme on a fresh installation of Kubuntu 20.04.2 along with kvantum and I realized that when I lock the screen, it is not working correctly, only shows a wallpaper but not the login controls so I'm not able to login again.

Also in the screenlocking configuration appears the following message:

> Error: Could not load: file://usr/share/plasma/look-and-feel/com.github.varlesh.materia/contents/lockscreen/config.qml:4 module "org.kde.kirigami" version 2.12 is not installed

![image](https://user-images.githubusercontent.com/84486349/126042702-cc634bd9-a916-4369-ada9-78dedc6b5891.png)

How screenlocking looks like
![1626537645061](https://user-images.githubusercontent.com/84486349/126042878-226abffb-8fb1-4593-a153-f941e3d2be6f.jpg)

My system info
![image](https://user-images.githubusercontent.com/84486349/126042733-13eeb66f-ffae-42f0-8995-dcd54d403cdd.png)

**Comment by varlesh** [comment]
@oltemo93 Fixed, please check it from git

**Comment by oltemo93** [comment]
> @oltemo93 Fixed, please check it from git

@varlesh Still not working, now another issue shows on screenlocking configuration

![image](https://user-images.githubusercontent.com/84486349/126076897-fc2bebe0-a6c4-43de-899a-81fd385bfa7f.png)

**Comment by varlesh** [comment]
hm... On latest plasma-workspace devs integrate Kirigami & KCM modules support. But Kubuntu have old Kdelacrative 5.68...
I'm try replace configs from 5.68 it's worked for me on KDE Neon, but not for Kubuntu (on VirtualBox).
@oltemo93 You can test it on real system?
`kate ~/.local/share/plasma/look-and-feel/com.github.varlesh.materia/contents/lockscreen/config.qml`
or
`kate /usr/share/plasma/look-and-feel/com.github.varlesh.materia/contents/lockscreen/config.qml`
and replace all code to this:
```
import QtQuick 2.5
import QtQuick.Controls 2.5 as QQC2
import QtQuick.Layouts 1.1

ColumnLayout {
    property alias cfg_alwaysShowClock: alwaysClock.checked
    property alias cfg_showMediaControls: showMediaControls.checked

    spacing: 0

    RowLayout {
        spacing: units.largeSpacing / 2

        QQC2.Label {
            Layout.minimumWidth: formAlignment - units.largeSpacing //to match wallpaper config...
            horizontalAlignment: Text.AlignRight
            text: i18nd("plasma_lookandfeel_org.kde.lookandfeel", "Clock:")
        }
        QQC2.CheckBox {
            id: alwaysClock
            text: i18ndc("plasma_lookandfeel_org.kde.lookandfeel", "verb, to show something", "Always show")
        }
        Item {
            Layout.fillWidth: true
        }
    }

    RowLayout {
        spacing: units.largeSpacing / 2

        QQC2.Label {
            Layout.minimumWidth: formAlignment - units.largeSpacing //to match wallpaper config...
            horizontalAlignment: Text.AlignRight
            text: i18nd("plasma_lookandfeel_org.kde.lookandfeel", "Media controls:")
        }
        QQC2.CheckBox {
            id: showMediaControls
            text: i18ndc("plasma_lookandfeel_org.kde.lookandfeel", "verb, to show something", "Show")
        }
        Item {
            Layout.fillWidth: true
        }
    }
}
```

**Comment by lukaskabc** [comment]
Hello, I have basically same issue - but with QQC.
![image](https://user-images.githubusercontent.com/28897542/126204377-a9aacb4b-97be-424b-b41e-908783532047.png)
![image](https://user-images.githubusercontent.com/28897542/126204487-38b2967d-3ef6-46e2-8e41-1a18fbed2beb.png)

**Comment by oltemo93** [comment]
> hm... On latest plasma-workspace devs integrate Kirigami & KCM modules support. But Kubuntu have old Kdelacrative 5.68...
> I'm try replace configs from 5.68 it's worked for me on KDE Neon, but not for Kubuntu (on VirtualBox).
> @oltemo93 You can test it on real system?
> `kate ~/.local/share/plasma/look-and-feel/com.github.varlesh.materia/contents/lockscreen/config.qml`
> or
> `kate /usr/share/plasma/look-and-feel/com.github.varlesh.materia/contents/lockscreen/config.qml`
> and replace all code to this:
> 
> ```
> import QtQuick 2.5
> import QtQuick.Controls 2.5 as QQC2
> import QtQuick.Layouts 1.1
> 
> ColumnLayout {
>     property alias cfg_alwaysShowClock: alwaysClock.checked
>     property alias cfg_showMediaControls: showMediaControls.checked
> 
>     spacing: 0
> 
>     RowLayout {
>         spacing: units.largeSpacing / 2
> 
>         QQC2.Label {
>             Layout.minimumWidth: formAlignment - units.largeSpacing //to match wallpaper config...
>             horizontalAlignment: Text.AlignRight
>             text: i18nd("plasma_lookandfeel_org.kde.lookandfeel", "Clock:")
>         }
>         QQC2.CheckBox {
>             id: alwaysClock
>             text: i18ndc("plasma_lookandfeel_org.kde.lookandfeel", "verb, to show something", "Always show")
>         }
>         Item {
>             Layout.fillWidth: true
>         }
>     }
> 
>     RowLayout {
>         spacing: units.largeSpacing / 2
> 
>         QQC2.Label {
>             Layout.minimumWidth: formAlignment - units.largeSpacing //to match wallpaper config...
>             horizontalAlignment: Text.AlignRight
>             text: i18nd("plasma_lookandfeel_org.kde.lookandfeel", "Media controls:")
>         }
>         QQC2.CheckBox {
>             id: showMediaControls
>             text: i18ndc("plasma_lookandfeel_org.kde.lookandfeel", "verb, to show something", "Show")
>         }
>         Item {
>             Layout.fillWidth: true
>         }
>     }
> }
> ```

I've replaced the code within that file with this new one,the error shown on the system settings don't appear already, but the lockscreen still not showing the login controls

![image](https://user-images.githubusercontent.com/84486349/126251417-e50fbb0e-fdde-4253-8d00-d1b897dee3a7.png)

the lockscreen still looking like this
![image](https://user-images.githubusercontent.com/84486349/126251614-f46f5eaf-8817-4fe6-a5bd-6aef28d223ca.png)

**Comment by varlesh** [comment]
Thx for test
I'm already downgrade lockscreen for Kubuntu 20.04 with compability with KDE Neon...
About Debian, not shure. Plasma 5.14.5 released in 2019, it's very old. But i try it

**Comment by varlesh** [comment]
@oltemo93 @lukaskabc Please test it

**Comment by oltemo93** [comment]
> @oltemo93 @lukaskabc Please test it

 @varlesh lockscreen is now working!

**Comment by varlesh** [comment]
Not need lock screen, you can test it with greet:
`/usr/lib/x86_64-linux-gnu/libexec/kscreenlocker_greet --testing --theme /usr/share/plasma/look-and-feel/com.github.varlesh.materia-dark`

**Comment by varlesh** [comment]
@oltemo93 thx, wait @lukaskabc

**Comment by lukaskabc** [comment]
`user@debian:~$ /usr/lib/x86_64-linux-gnu/libexec/kscreenlocker_greet --testing --theme /usr/share/plasma/look-and-feel/com.github.varlesh.materia-dark
OpenGL vendor string:                   Intel Open Source Technology Center
OpenGL renderer string:                 Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
OpenGL version string:                  3.0 Mesa 18.3.6
OpenGL shading language version string: 1.30
Driver:                                 Intel
GPU class:                              Unknown
OpenGL version:                         3.0
GLSL version:                           1.30
Mesa version:                           18.3.6
Linux kernel version:                   4.19
Requires strict binding:                yes
GLSL shaders:                           yes
Texture NPOT support:                   yes
Virtual Machine:                        no
kf5.kpackage: No metadata file in the package, expected it at: "/usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/"
kf5.kpackage: No metadata file in the package, expected it at: "/usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/"
kf5.kpackage: No metadata file in the package, expected it at: "/usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/"
Locked at 1626868681
kf5.kpackage: No metadata file in the package, expected it at: "/usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/"
kf5.kpackage: No metadata file in the package, expected it at: "/usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/"
kf5.kpackage: No metadata file in the package, expected it at: "/usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/"
kf5.kpackage: No metadata file in the package, expected it at: "/usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/"
kf5.kpackage: No metadata file in the package, expected it at: "/usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/"
kf5.kpackage: No metadata file in the package, expected it at: "/usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/"
file:///usr/share/plasma/look-and-feel/com.github.varlesh.materia-dark/contents/lockscreen/LockScreenUi.qml:62:5: SessionManagement is not a type
kf5.kpackage: No metadata file in the package, expected it at: "/usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/"
kf5.kpackage: No metadata file in the package, expected it at: "/usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/"
kf5.kpackage: No metadata file in the package, expected it at: "/usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/"
kf5.kpackage: No metadata file in the package, expected it at: "/usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/"
kf5.kpackage: No metadata file in the package, expected it at: "/usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/"
kf5.kpackage: No metadata file in the package, expected it at: "/usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/"
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
kf5.kpackage: No metadata file in the package, expected it at: "/usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/"
kf5.kpackage: No metadata file in the package, expected it at: "/usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/"
kf5.kpackage: No metadata file in the package, expected it at: "/usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/"
kf5.kpackage: No metadata file in the package, expected it at: "/usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/"
kf5.kpackage: No metadata file in the package, expected it at: "/usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/"
kf5.kpackage: No metadata file in the package, expected it at: "/usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/"
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
`
`sudo /usr/lib/x86_64-linux-gnu/libexec/kscreenlocker_greet --testing --theme /usr/share/plasma/look-and-feel/com.github.varlesh.materia-dark
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
OpenGL vendor string:                   Intel Open Source Technology Center
OpenGL renderer string:                 Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
OpenGL version string:                  3.0 Mesa 18.3.6
OpenGL shading language version string: 1.30
Driver:                                 Intel
GPU class:                              Unknown
OpenGL version:                         3.0
GLSL version:                           1.30
Mesa version:                           18.3.6
Linux kernel version:                   4.19
Requires strict binding:                yes
GLSL shaders:                           yes
Texture NPOT support:                   yes
Virtual Machine:                        no
QObject: Cannot create children for a parent that is in a different thread.
(Parent is ScreenLocker::UnlockApp(0x7ffce6a99a50), parent's thread is QThread(0x557b0208e310), current thread is QThread(0x557b020ee040)
QObject::installEventFilter(): Cannot filter events for objects in a different thread.
QObject: Cannot create children for a parent that is in a different thread.
(Parent is ScreenLocker::UnlockApp(0x7ffce6a99a50), parent's thread is QThread(0x557b0208e310), current thread is QThread(0x557b020ee040)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is ScreenLocker::UnlockApp(0x7ffce6a99a50), parent's thread is QThread(0x557b0208e310), current thread is QThread(0x557b020ee040)
QObject::installEventFilter(): Cannot filter events for objects in a different thread.
Locked at 1626868701
file:///usr/share/plasma/look-and-feel/com.github.varlesh.materia-dark/contents/lockscreen/LockScreenUi.qml:62:5: SessionManagement is not a type
^C
`

**Comment by varlesh** [comment]
@lukaskabc fixed

**Comment by lukaskabc** [comment]
working now, thank you
