### ISSUE TITLE
Better Kitigami app integration

### ISSUE THREAD

**Issue by sergioad** [PapirusDevelopmentTeam/materia-kde#121]
Hello, unlike normal KDE apps (Dolphin and Kate for example) the Kirigami and MauiKit apps lack the top bar theming, could you support them_Here are System Settings and NeoChat as examples

![Screenshot_20210720_154104](https://user-images.githubusercontent.com/5375145/126354987-436e21c7-bf5b-402f-9a45-180ee01a0424.png)
![Screenshot_20210720_154143](https://user-images.githubusercontent.com/5375145/126354992-9f1fabd0-01d2-43d9-bd86-8192f222d6b1.png)

**Comment by varlesh** [comment]
Kirigami/QML style hardcoded and adapted only for Breeze:
https://github.com/tsujan/Kvantum/issues/333

**Comment by sergioad** [comment]
Thanks, and sorry, yesterday by talking with people from the Maui project I
learned that the current maintainer of Kvantum refuses to give support to
QtQuick theming
