### ISSUE TITLE
Different active colors in menus

### ISSUE THREAD

**Issue by Dkoeddnsnp** [PapirusDevelopmentTeam/materia-kde#124]
Some menus have different colors for active items after update to Plasma 5.22. Sorry to bother if it is hardcoded and nothing can be done.
![Screenshot_20210727_231742](https://user-images.githubusercontent.com/66845002/127221870-c4778d49-8f62-43c5-bd9b-229dbd498b91.png)

**Comment by varlesh** [comment]
It's QML
https://github.com/PapirusDevelopmentTeam/materia-kde#blacklist-apps

**Comment by varlesh** [comment]
Try set Highlight color `#384252` on Materia Dark color scheme... It's solved this problem, but anyway qml not use ItemView widget from Kvantum theme
