### ISSUE TITLE
Windows Animation in KDE doesn't work

### ISSUE THREAD

**Issue by Zorrototo** [PapirusDevelopmentTeam/materia-kde#130]
When I select Materia Dark as my Windows Decoration in KDE Settings, it breaks the windows maximize animations. If I switch back to Breeze, I get a smooth maximizing animation, but with Materia it is like a two steps animation. Other Windows decorations I tried, like Plastik, do not break the animation either, so its seems it is an issue related to Materia Dark specifically.

**Comment by varlesh** [comment]
Materia theme does not handle the animation process.
It's only THEME!!!

**Comment by varlesh** [comment]
Request bug to KDE

**Comment by Zorrototo** [comment]
OK, I don't know why I have issue only when I enable the Materia Dark one though.

**Comment by varlesh** [comment]
About Plasttik, this theme write on C++ & QML and not have shadows or SVG elements. It makes no sense to compare it with the Materia theme.
https://github.com/KDE/kwin/tree/master/src/plugins/kdecorations/aurorae/themes/plastik/code
https://github.com/KDE/kwin/blob/master/src/plugins/kdecorations/aurorae/themes/plastik/package/contents/ui/main.qml

**Comment by Zorrototo** [comment]
Yes, and Breeze is C++ too (which works perfectly) I think.

**Comment by varlesh** [comment]
I know abot this lagg and see this, but i can't doing anything.
Materia's aurorae themes have very clean SVG code and i'm not have ideas how solve it.

**Comment by Zorrototo** [comment]
OK I just wanted to inform it here, now if there is nothing to do it's OK.

**Comment by varlesh** [comment]
I can only recommend some actions for better performance.
1. Disable effects **Translucency** & **Blur**
2. Set **Rendering engine** to **OpenGL 3.1**
3. Set **Rendering delay** to **Force the smoothest animation**
3. Set **Scaling method** to **With anti-aliasing**

**Comment by Zorrototo** [comment]
Thanks for advice ;)
