### ISSUE TITLE
Arrows in Dolphin breadcrumb bar are almost invisible with default Materia theme

### ISSUE THREAD

**Issue by jpenala** [PapirusDevelopmentTeam/materia-kde#132]
The arrows in Dolphin breadcrumb navigation bar are almost invisible with default Materia theme. In comparison they look fine with Materia Light and Materia Dark. Latest Materia KDE version installed with the official installer, Plasma 5.23.4, Fedora 35 KDE, theme set with Kvantum manager.

Default Materia
![default](https://user-images.githubusercontent.com/59263827/147388088-a0f1803e-7550-4974-a2da-9b1856c3669c.png)

Light
![light](https://user-images.githubusercontent.com/59263827/147388095-7a66b41e-8981-4a9a-83ba-6dcbbea487e8.png)

Dark
![dark](https://user-images.githubusercontent.com/59263827/147388097-82f4f5a7-4e58-4a42-af4c-d9a1c5791849.png)

**Comment by varlesh** [comment]
fixed

**Comment by jpenala** [comment]
Thank you!
