### ISSUE TITLE
Wrong minus (-) symbol in Panel edit mode

### ISSUE THREAD

**Issue by jpenala** [PapirusDevelopmentTeam/materia-kde#133]
When entering Panel edit mode, the panel size adjustment shows wrong symbol for decreasing panel size. Should be minus (-). Latest Materia KDE version installed with the official installer, Plasma 5.23.4, Fedora 35 KDE.

![panel-edit](https://user-images.githubusercontent.com/59263827/147388195-18dc7bdb-ab4e-4172-a016-dc1ffb821f78.png)

**Comment by varlesh** [comment]
fixed

**Comment by jpenala** [comment]
Thank you!
