### ISSUE TITLE
Materia Dark SDDM doesn't use system font settings

### ISSUE THREAD

**Issue by enkeyz** [PapirusDevelopmentTeam/materia-kde#135]
Is there a way to let Materia SDDM to use the system-wide font settings, like how Breath SDDM uses?

**Comment by varlesh** [comment]
Materia's SDDM themes created for more DE's and not have plasma dependencies.
But SDDM font can be changed on **/usr/lib/sddm/sddm.conf.d**, for example **00neon-theme.conf**:
```
[Theme]
Font=Oxygen
```
