### ISSUE TITLE
SDDM User Icon

### ISSUE THREAD

**Issue by ghost** [PapirusDevelopmentTeam/materia-kde#137]
Is there a way to change user icon for SDDM with this theme?
FacesDir=/var/lib/AccountsService/icons/
I checked with Arch Wiki and added this to the configuration file, but this method only works with the default breeze theme. 

I configured the theme.user.conf manually as well but it did not work either.

**Comment by varlesh** [comment]
Try it. User icon on KDE Neon used from hidden file `/home/USER/.face.icon`
Recommend size (for materia) 144x144px and higher.
Test it with SVG and PNG.
**NOTE** (Need use without extension): NOT `.face.icon.png` or `.face.icon.svg`

**Comment by varlesh** [comment]
as i know this file also used for KickOff & LockScreen too:
![image](https://user-images.githubusercontent.com/8083855/169690555-fc58e951-847a-4b45-bb01-e73cf767e88a.png)

**Comment by alinpr18** [comment]
> as i know this file also used for KickOff & LockScreen too: ![image](https://user-images.githubusercontent.com/8083855/169690555-fc58e951-847a-4b45-bb01-e73cf767e88a.png)

Not working

**Comment by skeezmoe** [comment]
Same here, tried all of the ways to set the user icon but still does not work. Please fix this because this theme is really great except for this bug.
