### ISSUE TITLE
Titlebar extremely pixelated and window decorations broken

### ISSUE THREAD

**Issue by major-mayer** [PapirusDevelopmentTeam/materia-kde#143]
Hi,
I just gave this theme a try on my KDE Plasma 5.24 desktop.
I like the design, but it seems to have some issues when dealing with a Wayland session and fractional scaling (125%) enabled.
![grafik](https://user-images.githubusercontent.com/17907799/177782340-a09cb973-68a8-4b9d-bf6b-fc4b03aac75f.png)
As you can see, the titlebar is extremely pixelated, the font is barely readable, and the shadows of that window stop somewhere in the middle.

When i switch to window decorations "breeze", it's looking a lot better:
![grafik](https://user-images.githubusercontent.com/17907799/177782830-8ce4d06c-ec1f-457f-b1b5-33f68f897cd7.png)
However the look doesn't really fit to this theme.
Oxygen also works:
![grafik](https://user-images.githubusercontent.com/17907799/177783151-bc1b7832-625c-43e1-9292-4b39155924a7.png)

Is there anything that I can do about it or that you could fix?
I am using an AMD card and open-source drivers.

**Comment by varlesh** [comment]
Aurorae very old engine. I cant't fix this :(

**Comment by major-mayer** [comment]
Oh that's a pity, but thanks for the clarification.
IMO people should stop recommending KDE for it's customization, at least in terms of theming.
Everything seems to be outdated, partially or not supported at all and only works for a fraction of the applications that you installed (especially since Kirigami or Libadwaita).
