### ISSUE TITLE
Wrong rendering of window borders

### ISSUE THREAD

**Issue by simonbcn** [PapirusDevelopmentTeam/materia-kde#146]
```
Operating System: Arch Linux
KDE Plasma Version: 5.25.2
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.18.10-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 64 × AMD Ryzen Threadripper 3970X 32-Core Processor
Memory: 62.6 GiB of RAM
Graphics Processor: AMD Radeon RX 580 Series

kvantum-theme-materia 20220607-1
materia-gtk-theme 20210322-2
materia-kde 20220607-1

$ cat ~/.Xresources
Xft.dpi:       109
Xft.antialias: true
Xft.hinting:   true
Xft.autohint:  false
Xft.hintstyle: hintslight
Xft.lcdfilter: lcddefault
Xft.rgba:      rgb
```

The DPI of my monitor is higher than 96.

I set the border size to No Borders in Window Decoration settings:
![2022-07-12_09-59](https://user-images.githubusercontent.com/428231/178439925-cb7d8417-5f8f-4516-ab18-f056b6226ab0.png)

But it still draws the edges and quite large ones at that:
![2022-07-12_10-01](https://user-images.githubusercontent.com/428231/178440390-6d83871b-ed9d-429a-ad80-d17c88c57ede.png)

**Comment by varlesh** [comment]
How it's worked with DPI 96p?

**Comment by varlesh** [comment]
I don't know  Brisa. If you mean Breeze it's another engine. Materia it's Aurorae theme. This engine very old and have more bugs.
You can report this to KDE Bug Tracker. Padding on SVG and RC Right and Default 96 DPI worked fine. I can't release hundreds of releases for each specific DPI values
