### ISSUE TITLE
Adaptive opacity support for KDE panel

### ISSUE THREAD

**Issue by onnyyonn** [PapirusDevelopmentTeam/materia-kde#147]
KDE panels can have an option for adaptive opacity if the following is in the metadata desktop file:
```
[AdaptiveTransparency]
enabled=true
```

Can you please add this to Materia?

**Comment by onnyyonn** [comment]
Here is the relevant merge https://invent.kde.org/plasma/plasma-desktop/-/merge_requests/97

**Comment by varlesh** [comment]
i'm not understand why this needed on Materia's themes. Our panel not have opacity

**Comment by onnyyonn** [comment]
That is what I am requesting. Are you open to implementing opacity? The panel will not be transparent by default. But the users will have an option to choose full or adaptive transparency.

If you need it, I can try to create a PR to implement this feature.

**Comment by varlesh** [comment]
It's can be implementing only on panels or dialogs (widgets) too? How it's will be worked with old Plasma versions, for example LTS?

**Comment by varlesh** [comment]
hm... i'm test it with dialogs and this worked too. Very interested

**Comment by varlesh** [comment]
But it's worked wrong... When i'm set opaque option - dialogs applying color from panel:
For example, panel-background 20% opacity color `#121212` and dialogs/background 20% opacity color `#1e1e1e`
![image](https://user-images.githubusercontent.com/8083855/182010260-7b825a36-f365-4c63-a312-87b563fc4be4.png)

**Comment by varlesh** [comment]
That is, when adding the `[AdaptiveTransparency] enabled=true option`, the widget color is applied from the panel color, which violates the original implementation of the style.

**Comment by varlesh** [comment]
How it should look like:
![image](https://user-images.githubusercontent.com/8083855/182010390-eb97d3cb-5661-4c92-9460-5c30e12fd286.png)

**Comment by onnyyonn** [comment]
Yes the transparency applies to dialogs too. Here is the relevant merge https://invent.kde.org/frameworks/plasma-framework/-/merge_requests/119/

If the dialogs are taking color of the panel, that is probably a bug!

**Comment by onnyyonn** [comment]
> How it's will be worked with old Plasma versions, for example LTS?
It will not be available for old Plasma versions.

**Comment by varlesh** [comment]
Well, since this is an error and there is no support for the LTS version, I think we should not add this option.
