### ISSUE TITLE
Stuck on lock screen

### ISSUE THREAD

**Issue by enkeyz** [PapirusDevelopmentTeam/materia-kde#151]
After installing the newest Manjaro, and making this as the login screen(System settings -> Startup -> Login screen), strange things happening: when I'm on lock screen and entered my password and pressed Enter, nothing happens(also nothing when clicking on the button). When I try to switch users, I get the login screen as usual, entered my password, and getting black screen after the animated KDE logo.

KDE Plasma: 5.24.6
KDE Framework: 5.96.0
Qt version: 5.15.5

It's a fresh install, and everything working with the default theme.

**Comment by varlesh** [comment]
Maybe you mean SDDM?

**Comment by varlesh** [comment]
Usualy for starup it's SDDM. Try this PR: https://github.com/PapirusDevelopmentTeam/materia-kde/pull/138

**Comment by enkeyz** [comment]
I stole this image from an another issue(https://github.com/PapirusDevelopmentTeam/materia-kde/issues/142):

On the login form, nothing happens after I enter my password and press Enter: https://user-images.githubusercontent.com/8083855/176799877-18071cfd-038b-4f80-b398-346e4b147524.png

**Comment by varlesh** [comment]
I can't reproduce this issue. Also 'respond' have only single match on KDE repo:
https://github.com/KDE/plasma-workspace/search?q=respond

**Comment by varlesh** [comment]
My specs:
Operating System: KDE neon 5.25
KDE Plasma Version: 5.25.4
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5

@enkeyz You use Wayland or X11? You try change display server?

**Comment by enkeyz** [comment]
X11. And My KDE Plasma version is 5.24.6.

Maybe it's a Manjaro configuration issue?

**Comment by varlesh** [comment]
> Maybe it's a Manjaro configuration issue? It's a completely fresh install. Never had something like this before.

I don't know. I use X 11 too.
[Peek 2022-08-22 11-11.webm](https://user-images.githubusercontent.com/8083855/185860953-ebdbb51d-2e93-4740-a30d-caee6ec4c03d.webm)

**Comment by enkeyz** [comment]
I've no idea. I just reinstalled Manjaro three times already, to see if this issue is persistent or not on a fresh install.

**Comment by varlesh** [comment]
I found this info:
https://www.reddit.com/r/openSUSE/comments/vl1rwi/kscreenlocker_can_not_be_unlocked_anymore_x11/

**Comment by enkeyz** [comment]
Okey, but what now?

**Comment by varlesh** [comment]
> X11. And My KDE Plasma version is 5.24.6.

Ough!!! Latest release ONLY support Plasma 5.25 and higher. See changelogs on releases! Try [20220607](https://github.com/PapirusDevelopmentTeam/materia-kde/releases/tag/20220607)

**Comment by enkeyz** [comment]
Oh shit :D

**Comment by varlesh** [comment]
Very strange maintainers.... They update materia-kde, but not plasma
https://software.manjaro.org/package/materia-kde

**Comment by enkeyz** [comment]
Probably should make a post on forum.

**Comment by varlesh** [comment]
It's my fault too i forgot to write about plasma version support.
But now added this.

**Comment by enkeyz** [comment]
Opened a post: https://forum.manjaro.org/t/newest-materia-kde-in-the-repo-only-supports-plasma-5-25-and-up/120070

**Comment by varlesh** [comment]
@enkeyz Please test previous release, if worked please post message on forum.
I will be grateful to you!

**Comment by enkeyz** [comment]
Yeah, previous release doesn't have this issue. I take this PR is the issue https://github.com/PapirusDevelopmentTeam/materia-kde/commit/bc91867782e3bf1f89a84cea9ed9fd690849373d

**Comment by varlesh** [comment]
Thx! Ok, closed.

**Comment by varlesh** [comment]
> Yeah, previous release doesn't have this issue. I take this PR is the problem https://github.com/PapirusDevelopmentTeam/materia-kde/commit/bc91867782e3bf1f89a84cea9ed9fd690849373d

Yes. KDE Devs very serious change API and newest lockscreens not support previous Plasma versions.
https://github.com/KDE/plasma-workspace/commit/3422348c5216078f598954c4b7c7e0fc902ce3b7

**Comment by philmmanjaro** [comment]
Please check if 20220714-1.0 package fixes the issue as it comes with `patch -Rp1 -i ../bc91867782e3bf1f89a84cea9ed9fd690849373d.patch` reverting the lockscreen port to 5.25.

**Comment by mojolo** [comment]
you may want to fix the release in the ubuntu Jammy ppa. Jammy '22.04' ppa has materia-kde version `20220823` available but it's only on Plasma 5.24.4. as a result, the lock screen login is broken.

**Comment by varlesh** [comment]
@mojolo I don't know how doing better... Because KDE Neon now use Plasma 5.25.4 and more users used this distro, but [20220607](https://github.com/PapirusDevelopmentTeam/materia-kde/releases/tag/20220607) release not compability with new Plasma version.

**Comment by mojolo** [comment]
thank you anyway. KDE always has issues but that's part of the reason we love it! next version i'm sure things will be OK!!
