### ISSUE TITLE
Lockscreen - unable to submit

### ISSUE THREAD

**Issue by lukaskabc** [PapirusDevelopmentTeam/materia-kde#152]
Hello,
I just upgraded kubuntu to ubuntu 22 and installed materia-kde, I found one problem with the lock screen - after submit nothing happens

System info:
![image](https://user-images.githubusercontent.com/28897542/192252345-dc717a64-095a-47f0-a32a-00ef15eecb84.png)

log:
`/usr/lib/x86_64-linux-gnu/libexec/kscreenlocker_greet --testing --theme /usr/share/plasma/look-and-feel/com.github.varlesh.materia-dark`

```file:///usr/share/plasma/look-and-feel/com.github.varlesh.materia-dark/contents/lockscreen/LockScreenUi.qml:37:5: QML Connections: Detected function "onInfoMessage" in Connections element. This is probably intended to be a signal handler but no signal of the target matches the name.
file:///usr/share/plasma/look-and-feel/com.github.varlesh.materia-dark/contents/lockscreen/LockScreenUi.qml:37:5: QML Connections: Detected function "onErrorMessage" in Connections element. This is probably intended to be a signal handler but no signal of the target matches the name.
file:///usr/share/plasma/look-and-feel/com.github.varlesh.materia-dark/contents/lockscreen/LockScreenUi.qml:37:5: QML Connections: Detected function "onPrompt" in Connections element. This is probably intended to be a signal handler but no signal of the target matches the name.
file:///usr/share/plasma/look-and-feel/com.github.varlesh.materia-dark/contents/lockscreen/LockScreenUi.qml:37:5: QML Connections: Detected function "onPromptForSecret" in Connections element. This is probably intended to be a signal handler but no signal of the target matches the name.
file:///usr/share/plasma/look-and-feel/com.github.varlesh.materia-dark/contents/lockscreen/LockScreenUi.qml:225: ReferenceError: wallpaper is not defined
Locked at 1664187202
file:///usr/share/plasma/look-and-feel/com.github.varlesh.materia-dark/contents/lockscreen/LockScreenUi.qml:146: Error: Insufficient arguments
file:///usr/share/plasma/look-and-feel/com.github.varlesh.materia-dark/contents/lockscreen/LockScreenUi.qml:331: TypeError: Property 'respond' of object Authenticator(0x5594b1434290) is not a function
```

**Comment by sirish-bajpai** [comment]
I am getting same problem. Entering password in lock screen and submit. Nothing happens.
./kscreenlocker_greet --testing
file:///usr/share/plasma/look-and-feel/com.github.varlesh.materia-light/contents/lockscreen/LockScreenUi.qml:37:5: QML Connections: Detected function "onInfoMessage" in Connections element. This is probably intended to be a signal handler but no signal of the target matches the name.
file:///usr/share/plasma/look-and-feel/com.github.varlesh.materia-light/contents/lockscreen/LockScreenUi.qml:37:5: QML Connections: Detected function "onErrorMessage" in Connections element. This is probably intended to be a signal handler but no signal of the target matches the name.
file:///usr/share/plasma/look-and-feel/com.github.varlesh.materia-light/contents/lockscreen/LockScreenUi.qml:37:5: QML Connections: Detected function "onPrompt" in Connections element. This is probably intended to be a signal handler but no signal of the target matches the name.
file:///usr/share/plasma/look-and-feel/com.github.varlesh.materia-light/contents/lockscreen/LockScreenUi.qml:37:5: QML Connections: Detected function "onPromptForSecret" in Connections element. This is probably intended to be a signal handler but no signal of the target matches the name.
file:///usr/share/plasma/look-and-feel/com.github.varlesh.materia-light/contents/lockscreen/LockScreenUi.qml:225: ReferenceError: wallpaper is not defined
Locked at 1664195419
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
QXcbClipboard: SelectionRequest too old
file:///usr/share/plasma/look-and-feel/com.github.varlesh.materia-light/contents/lockscreen/LockScreenUi.qml:146: Error: Insufficient arguments
file:///usr/share/plasma/look-and-feel/com.github.varlesh.materia-light/contents/lockscreen/LockScreenUi.qml:331: TypeError: Property 'respond' of object Authenticator(0x55b9c439c730) is not a function

Operating System: Ubuntu 22.04
KDE Plasma Version: 5.24.6
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-48-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-8265U CPU @ 1.60GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

**Comment by varlesh** [comment]
Please read release notes. Old plasma versions not supported.
Downgrade on release https://github.com/PapirusDevelopmentTeam/materia-kde/releases/tag/20220607
