### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by groeffen** [PapirusDevelopmentTeam/materia-kde#155]
Is development for this theme still active? I saw the owners had an fallout of the Russian invasion of Ukraine in another repository and was wondering if development would still continue. This is by far my favorite theme for Plasma so i'd be an shame if this would become abandonware.

**Comment by SmartFinn** [comment]
It seems to me @varlesh still uses the Kvantum theme, so you can look forward to updates that keep it works on the latest KDE Plasma.

I am a GNOME user, so I pay much less attention to this project.

**Comment by gijsrrr** [comment]
Thanks - With the Qt6 compatibility this theme will hopefully be solid for years to come!
