### ISSUE TITLE
Color issue

### ISSUE THREAD

**Issue by micleb** [PapirusDevelopmentTeam/materia-kde#17]
Hello,

I just installed Material kde theme, great job, it's awesome !

But I have a little problem : checkbox, radio buttons and range slide do not have the same color as the rest of the DE (or the rest of the DE doesn't have the same color as the buttons)

See for example the next screenshot

![screenshot_20180711_175602](https://user-images.githubusercontent.com/22656213/42584711-21475a26-8534-11e8-85c8-0ddaec92bfc3.png)

Checkbox, radio buttons etc are in teal where as the selected folder are in blue.

How can I fix that ?

Thank you.

**Comment by dooqob** [comment]
Check the original [materia-theme](https://github.com/nana-4/materia-theme) GTK
![widget-factory](https://user-images.githubusercontent.com/21042432/42983461-26ba6430-8be7-11e8-8d6b-20213478ee6f.png)

**Comment by micleb** [comment]
Oh right, I believed it was a mistake. Thank you, issue solved.
