### ISSUE TITLE
[Kvantum] [MateriaBlur] Dolphin File Renaming Issue

### ISSUE THREAD

**Issue by mockroot** [PapirusDevelopmentTeam/materia-kde#18]
While changing the file name in Dolphin, text remains on the background, which makes it difficult to read.
Only reproducible with MateriaBlur. Other versions are fine.

![materia-blur](https://user-images.githubusercontent.com/24863704/43170939-5a955022-8fb0-11e8-93b3-0c1868c94749.gif)

**Comment by varlesh** [comment]
I can fix that, but we lost  translucency for window.

**Comment by varlesh** [comment]
fixed

**Comment by varlesh** [comment]
Maybe this fixed soon on Kvantum... wait:
https://github.com/tsujan/Kvantum/issues/234#issuecomment-408868089

**Comment by varlesh** [comment]
@mockroot revert last commit, because this worked fine with fresh git-version kvantum
