### ISSUE TITLE
Things that should be fixed

### ISSUE THREAD

**Issue by Warmuser** [PapirusDevelopmentTeam/materia-kde#19]
Hi, I'm an huge fan of Materia theme, that's why is my default theme for my KDE on my Distros. Anyway, I want to ask you If you can fix these little things:

1. Space between windows.
![fm01](https://user-images.githubusercontent.com/19243318/44383583-76298c80-a519-11e8-911c-b5facb3d9842.png)

2. Little grey margin in the corners. (It depends by the rounded corner, so I would like to ask you If you can fix it or release a version with squared margin against the rounded).

3. Browsers are not supported. (Chromium, Firefox, etc.. The theme doesn't match completely. But It can be resolved with a Materia theme for these Browsers).
![fm02](https://user-images.githubusercontent.com/19243318/44383584-76298c80-a519-11e8-9260-75af28efbf07.png)
![fm03](https://user-images.githubusercontent.com/19243318/44383819-5b0b4c80-a51a-11e8-9312-21e7c236b5c6.png)

4. The KDE Blur effect works on the mouse menus but doesn't work on the Terminal. It's because of the color settings? I can't figure what's the problem.

5. Any news for the SDDM theme? Someone will realease it soon?

Thanks

**Comment by varlesh** [comment]
> Space between windows.

I try fix that, but not promise. It's reproduced on other aurorae decorations?

> Little grey margin in the corners. (It depends by the rounded corner, so I would like to ask you If you can fix it or release a version with squared margin against the rounded).

blur with shadow aurorae decoration - it's KDE bug, see README:
https://github.com/PapirusDevelopmentTeam/materia-kde#known-issues

> Browsers are not supported. (Chromium, Firefox, etc.. The theme doesn't match completely. But It can be resolved with a Materia theme for these Browsers).

Firefox and Chromium - it's GTK apps. This customize for only Qt-apps!!! As alternative - use Falkon.

> The KDE Blur effect works on the mouse menus but doesn't work on the Terminal. It's because of the color settings? I can't figure what's the problem.

worked, why not?! You can added 10% opacity background to Konsole color profile on Materia Dark
![image](https://user-images.githubusercontent.com/8083855/44385180-a8de7f80-a52f-11e8-97f7-624403b44c5b.png)

> Any news for the SDDM theme? Someone will realease it soon?

maybe. But i'm not programmer and don't know QML

**Comment by varlesh** [comment]
@Warmuser aurorae fixed

**Comment by varlesh** [comment]
also for better looking i recommend use tiny panel for tray icons (22px) and software for better looking.
Some examples and screens you can see here:
https://github.com/PapirusDevelopmentTeam/materia-kde/tree/master/screens

**Comment by varlesh** [comment]
idea for Materia theme - it's monochrome icons for panel and material (colorized) for notification or tooltip:
![image](https://user-images.githubusercontent.com/8083855/44393610-388f2880-a546-11e8-9bf6-534952482744.png)

**Comment by Warmuser** [comment]
Answers for your questions: https://github.com/PapirusDevelopmentTeam/materia-kde/issues/19#issuecomment-414569216

1. Yes it happen also with other themes.

2. Ok

3. For me doesn't work. I don't know why there is no blur effect.

**Comment by Warmuser** [comment]
I prefer the colored version. But anyway thanks.

**Comment by Warmuser** [comment]
Ok, I finally find the setting to add the transparency to the terminal. Was not a theme problem, I'm sorry. Anyway I can't notice differencies with the gtk theme. The browser tab doesn't match the color into a single color. I'll show you:

![fd05](https://user-images.githubusercontent.com/19243318/44448196-d9cfba80-a5ea-11e8-8286-bc3b4131d1f1.png)

**Comment by Warmuser** [comment]
Ok, the aurorae theme seems to work perfectly. Thanks!
