### ISSUE TITLE
Selected font color

### ISSUE THREAD

**Issue by archqob** [PapirusDevelopmentTeam/materia-kde#2]
First, i want to thank you for your hard work to bring awesome GTK+ themes to KDE.

~~1- in plasma-menu pop-up menu still has adapta's color & assests like checkbox~~
![screenshot_20180415_220341](https://user-images.githubusercontent.com/21042432/38782835-a66d4b7c-40f9-11e8-9e2e-bd6e82372d92.png)

2- selection font color is hard to read
![screenshot_20180415_220528](https://user-images.githubusercontent.com/21042432/38782836-a6aa0ac6-40f9-11e8-83f3-e141c4139dca.png)

3- search box has white background outside its border
![x](https://user-images.githubusercontent.com/21042432/38782864-55021500-40fa-11e8-86cd-3d6aac0103ba.png)

UPDATE 1: Issue (1) has been solved after clearing cache

**Comment by varlesh** [comment]
It's not not Materia searchbox:
![image](https://user-images.githubusercontent.com/8083855/38789757-7caec8fc-414d-11e8-9b52-2689338771bc.png)
Selection color... hm it's strange. On other windows used white text color

**Comment by varlesh** [comment]
@tsujan Hi, itemview not use `text.press.color` on `kcmshell5 kcm_networkmanagement`. It's hardcoded?

**Comment by varlesh** [comment]
Config:
```
[ItemView]
inherits=PanelButtonCommand
text.margin=0
frame.element=itemview
interior.element=itemview
frame.top=2
frame.bottom=2
frame.left=2
frame.right=2
text.margin.top=2
text.margin.bottom=2
text.margin.left=4
text.margin.right=4
text.normal.color=#5c616c
text.focus.color=#5c616c
text.press.color=white
text.toggle.color=white
min_width=+0.3font
min_height=+0.3font
frame.expansion=0
```
result (on only kcmshell5 kcm_networkmanagement):
![image](https://user-images.githubusercontent.com/8083855/38790400-1e23409c-4152-11e8-89c7-e607c76dabe1.png)

**Comment by tsujan** [comment]
@varlesh Whenever you see such things, you could be sure that there's a problem in the app code.

**Comment by Warmuser** [comment]
There is a problem to fix, not every section title is restyled correctly:

![usf](https://user-images.githubusercontent.com/19243318/39617030-6240712a-4f7e-11e8-9889-5b55ffd390d7.png)

**Comment by tsujan** [comment]
@Warmuser  That side-pane is written in QML, not Qt. QML doesn't follow QStyle completely. By introducing QML into Plasma5, KDE developers created such problems. They also made a poor Qt style called "Breeze" to hide those problems but even Breeze can't hide them completely:

![breeze](https://user-images.githubusercontent.com/981076/39628325-fb98e66a-4fbd-11e8-9eef-affb7a246e12.png)

Nothing can be done by a Qt style engine for fixing those issues. They will be fixed if KDE developers purge Plasma5 from QML but, apparently, they're doing the opposite and turning KDE into a "QML Desktop Environment" (QMLDE).

**Comment by Warmuser** [comment]
Ok, thanks for the explication :)
