### ISSUE TITLE
Bug in Notification system tray icon

### ISSUE THREAD

**Issue by trmdi** [PapirusDevelopmentTeam/materia-kde#20]
Please see the screenshot, the first icon:
![image](https://user-images.githubusercontent.com/11857205/46390213-f1798300-c700-11e8-8358-90957fc88742.png)

**Comment by trmdi** [comment]
Btw, an off-topic question, do you have this bug or just me? https://bugs.kde.org/show_bug.cgi?id=399231

**Comment by varlesh** [comment]
It's kmail bug. Icon not used from plasma theme. 
Used icon from current icon theme with low icon size (i think 22px) or bugged rendered...

**Comment by varlesh** [comment]
Anyway icon not used from plasma for notification:
https://github.com/PapirusDevelopmentTeam/materia-kde/blob/master/plasma/desktoptheme/Materia/icons/kmail.svg
For mostly KDE apps used 32px icon for notification
