### ISSUE TITLE
double click to open things kde setting no longer functioning

### ISSUE THREAD

**Issue by kinghat** [PapirusDevelopmentTeam/materia-kde#21]
when i use materia my setting of double click to open things in kde is not respected and everything in single click. in kvantum under misc the dbl click option is not selectable:
![image](https://user-images.githubusercontent.com/16073360/46687366-5aa93c80-cbc0-11e8-9581-f42824746dbe.png)
im on kubuntu bionic.

**Comment by varlesh** [comment]
**Disable Respect current DE if possible** and **Enable Double-click**
