### ISSUE TITLE
Is there any quick way to convert all system tray icons to another color?

### ISSUE THREAD

**Issue by trmdi** [PapirusDevelopmentTeam/materia-kde#24]
Hi,
I really like your theme's icons, it looks much better than the default KDE ones.
But they are only usable for dark themes, is there any automatic way to change the color of all system tray icons to another, e.g black, to use them with light background panels ?

**Comment by varlesh** [comment]
It's easy, use sed )). For example:
```
cd /usr/share/plasma/desktoptheme/Materia/icons/
sudo sed -i s/dfdfdf/YOURCOLOR/g *.svg
```

**Comment by varlesh** [comment]
But this command change icons for KDE (and some Qt) apps. If you want change color on all icons, you must change color to icon theme too..

**Comment by trmdi** [comment]
Another way is to use Latte dock.
