### ISSUE TITLE
HiDPI skin for Yakuake

### ISSUE THREAD

**Issue by delfianto** [PapirusDevelopmentTeam/materia-kde#25]
The default yakuake skin is too small for HiDPI display, would be great if you could provide additional version which scaled 1.5x and 2x.

This is because yakuake is buggy if you set the screen scale to any value higher than 1x (off-center dropdown, graphical glitches in the terminal section) so I have to use 1x display scale with font DPI set to 144. While normal konsole works fine with this settings, the yakuake controls (skin) is too small for comfortable operation.

**Comment by varlesh** [comment]
HiDPI looks ugly, because used PNG's elements...

**Comment by delfianto** [comment]
So yakuake skin does not use SVG for resources? If so then this is a major bummer, probably I will use Konsole for now until yakuake has a new version that support HiDPI properly.

**Comment by varlesh** [comment]
@delfianto Skin redraw with vector SVG graphics. Please check it

**Comment by varlesh** [comment]
Tested with Yakuake 3.0.5 (on Full HD only):
![image](https://user-images.githubusercontent.com/8083855/50415844-cea9c700-0836-11e9-8b4a-385070ee50a7.png)

**Comment by delfianto** [comment]
Just installed the new yakuake skins, on 4k display the controls (UI elements) still looks very small.

<img width="1217" alt="screenshot_20181226_131803" src="https://user-images.githubusercontent.com/2359896/50434668-bc03c080-0910-11e9-9f68-8284b331ffec.png">

**Comment by varlesh** [comment]
@delfianto I really don't  know how solve this problem. All elements now on vector graphic  and use SVG's... Maybe need increase scale, but this meaningless, because used SVG's.
I think need ask about that on Yakuake developers

**Comment by delfianto** [comment]
I agree with your statement. This is most probably a bug with yakuake and how they handle rendering UI in hidpi display.

**Comment by varlesh** [comment]
@delfianto Maybe need try set DPI config for better rendering?
For example my config **~/.Xresources**:
```
Xft.dpi:       96
Xft.antialias: true
Xft.hinting:   true
Xft.autohint:  false
Xft.hintstyle: hintslight
Xft.lcdfilter: lcddefault
Xft.rgba:      rgb 
```
I think need try set change DPI to:
`Xft.dpi:       192`

**Comment by varlesh** [comment]
After changes > reboot pc

**Comment by delfianto** [comment]
Already tried that, and still no effect on the size of the UI controls. This is more likely not just a Yakuake bug but related to how KDE handles HiDPI scaling (which is not 100% perfect yet). If I set the display scaling to 1.5x or 2x everything works perfectly and not blurry, although with this config some app will act strangely (mis-aligned UI, blurry icons, or downright crashing).

Will close this issue as the UI element is no longer blurry and this is not really a theme skins issue anymore but more related to KDE in general.

Thank you for your time.
