### ISSUE TITLE
[Icon request] Mailspring System tray Icon

### ISSUE THREAD

**Issue by now-im** [PapirusDevelopmentTeam/materia-kde#26]
Mailspring is a mail app for Linux. It has system icon which is not visible in adapta or maetaria. As adpata theme issue is turned off I am reporting here for both of it. The two-dot besides wifi icon is the app icon. At the startup it turn into a total black block.
 
![image](https://user-images.githubusercontent.com/22009014/48955066-5a99ac00-ef76-11e8-85d3-43518018b15f.png)

**Comment by now-im** [comment]
Leave a comment if you need any icon info.

**Comment by varlesh** [comment]
run libappindicator-apps wit Unity environment option:
`XDG_CURRENT_DESKTOP=Unity mailspring`
It's KDE bug:
https://bugs.kde.org/show_bug.cgi?id=366062
