### ISSUE TITLE
Search Bar on Firefox isn't visible 

### ISSUE THREAD

**Issue by XEmpty** [PapirusDevelopmentTeam/materia-kde#27]
hi like above i see all the times the same problem with black text and dark background on firefox , even if i change "theme" on firefox i see the same problem. 

But this is strange problem cuz, work / don't work on random websites. 

For example : dropbox don't work.
Archlinux: Working

I mean input bars for writing text.

**Comment by SmartFinn** [comment]
All of those apps are GTK-apps that not using Materia-KDE. It's related to GTK theme https://github.com/nana-4/materia-theme/issues
