### ISSUE TITLE
Highlight border not concordant with panel's screen edge

### ISSUE THREAD

**Issue by hfel** [PapirusDevelopmentTeam/materia-kde#29]
See the image below.

![image](https://user-images.githubusercontent.com/16854594/49534459-de7e5d00-f8c1-11e8-8517-d772eb665b72.png)

The blue border should be on the left edge of the icon in this case, not below, and vice versa for a vertical panel at the right edge of the screen.

**Comment by varlesh** [comment]
updated

**Comment by varlesh** [comment]
update to git-version from AUR or sources:
![image](https://user-images.githubusercontent.com/8083855/51442140-431b3d00-1cf3-11e9-9428-bb1e8f3be442.png)

**Comment by hfel** [comment]
Got the updated version finally. I have to point out a little pickle still though -- shouldn't the border on the vertical panel be _to the left_ of the icon, so that it hugs the screen's edge as on the bottom bar?
