### ISSUE TITLE
[Suggestion]: Search box entry

### ISSUE THREAD

**Issue by archqob** [PapirusDevelopmentTeam/materia-kde#3]
I think it would be nicer to make search box style with transparent background like the GTK+ theme.
What do you think ?
![screenshot_20180415_225532](https://user-images.githubusercontent.com/21042432/38783322-75acc56a-4100-11e8-815b-8fdd1bc95164.png)
![screenshot_20180415_225837](https://user-images.githubusercontent.com/21042432/38783327-8e661624-4100-11e8-9c29-d85fbc77dd89.png)

**Comment by varlesh** [comment]
changed
