### ISSUE TITLE
Is there a light version?

### ISSUE THREAD

**Issue by h0cheung** [PapirusDevelopmentTeam/materia-kde#32]

**Comment by trmdi** [comment]
I think he meant the plasma theme.

**Comment by haoyet** [comment]
> Light version available:
> ![image](https://user-images.githubusercontent.com/8083855/50878531-a2727680-13f0-11e9-8b74-201fb9094eaf.png)

Is there a Materia Light plasma theme or look-and-feel theme?
The notification badges and application indicators on latte dock are not contrasting colors made them quite hard to see

**Comment by Howard-00** [comment]
> > Light version available:
> > ![image](https://user-images.githubusercontent.com/8083855/50878531-a2727680-13f0-11e9-8b74-201fb9094eaf.png)
> 
> Is there a Materia Light plasma theme or look-and-feel theme?
> The notification badges and application indicators on latte dock are not contrasting colors made them quite hard to see

Well, but I want a version with light topbar and dock.

**Comment by trmdi** [comment]
@Howard-00
You could try Latte dock, it has an option for inverting the color.

**Comment by haoyet** [comment]
> 
> 
> > > Light version available:
> > > ![image](https://user-images.githubusercontent.com/8083855/50878531-a2727680-13f0-11e9-8b74-201fb9094eaf.png)
> > 
> > 
> > Is there a Materia Light plasma theme or look-and-feel theme?
> > The notification badges and application indicators on latte dock are not contrasting colors made them quite hard to see
> 
> Well, but I want a version with light topbar and dock.

That's what exactly I was asking @varlesh for, Plasma theme is what decides the color of the top bar.

And to clarify my second point, this is what I meant the notification badge and the opened app indicator.
The notification is just poorly colored, the text color and the background color are both pretty dark so they create almost no contrast. 
As for the app indicator thing, I just thought if they could change it to a brighter color so it still would create contrast on the dark parts of the wallpaper(in this case, the indicator below Discord is quite hard to see)

![image](https://user-images.githubusercontent.com/28365438/54882866-d3314c00-4e34-11e9-8fcb-5ef6ab88893c.png)

And I believe Plasma theme also decides what these colors are, so a light version of the plasma theme would appreciated.

**Comment by y-usuzumi** [comment]
I would like a light version of plasma theme too!

It is an inconsistence if we have light versions of window decorations and color schemes but not a plasma theme. Also this would break some icons: if I select a light icon theme, e.g. Papirus-Light, the black icons would drown in the black bar; if I select a dark icon theme then these icons would drown in other places.

**Comment by varlesh** [comment]
moved here #66
