### ISSUE TITLE
The blur effect of MateriaBlur only covers half of the window on a device with high dpi display with fractal scaling factor.

### ISSUE THREAD

**Issue by ZZZXXX0110** [PapirusDevelopmentTeam/materia-kde#33]
As seen in the image below, only part of a window is blurred, such as this Konsole window. The same problem is seen on all other windows with themed element. The problem disappears when changing Widget Style in settings to anything other than Kvantum.

![image](https://user-images.githubusercontent.com/37162057/51068304-52f79a80-15ea-11e9-99ef-be73c6c89747.png)

This problem is encountered with Kubuntu 18.10 running on a Surface Pro 6.

**Comment by varlesh** [comment]
on your screen not Materia theme. Also for Konsole/Yakuake set manualy opacity on Profile settings (on all themes used 5% by default):
![image](https://user-images.githubusercontent.com/8083855/51069479-36d71600-1649-11e9-8fd9-a2ccf4497f3f.png)
Anyway i can't have HiDPi devices and can not test this

**Comment by ZZZXXX0110** [comment]
Changing screen scaling to an integer fixed this problem.

**Comment by varlesh** [comment]
ok, closed
