### ISSUE TITLE
Desktop theme with monochrome tray icons

### ISSUE THREAD

**Issue by mvolf** [PapirusDevelopmentTeam/materia-kde#35]
It would be great if we could have Plasma desktop theme with monochrome tray icons, similar as Arc has it:
- Arc Dark which uses colourful icons
- Arc Colour which uses colour from KDE colour scheme for icons

I know that we can use small panel to get monochrome icons in tray, but for me this makes the panel too small and icons hardly visible (4K resolution). The approach Arc has is better IMO.

**Comment by updateing** [comment]
This image could make it clearer:

![tray_icon_scale_2x_1x](https://user-images.githubusercontent.com/6023221/52488264-59f8d500-2bb7-11e9-944d-2f8e4f6a6015.png)

The top row is taken from theme preview, and the bottom row is what gets shown when "Scale Display" is set to 2x. If it's 1x, the icons will be monochrome just like the preview, but that's unusable on HiDPI displays.

**Comment by varlesh** [comment]
Idea for  colorized icons - it's notification/tooltip icons...
For example:
![image](https://user-images.githubusercontent.com/8083855/52517854-3ab38380-2c5b-11e9-8497-2336e7fe7694.png)
For fix that on hidpi display i must redraw all icons and we lost this idea. Maybe on Plasma theme available set  another scale or on **Xresources**?
example **~.Xresources**:
```
Xft.dpi:       96
Xft.antialias: true
Xft.hinting:   true
Xft.autohint:  false
Xft.hintstyle: hintslight
Xft.lcdfilter: lcddefault
Xft.rgba:      rgb 
```

**Comment by varlesh** [comment]
guys you set scale option on **~.xprofile**?
`QT_SCALE_FACTOR=2`

**Comment by varlesh** [comment]
i'm not have 4K-display and can't test this :(

**Comment by varlesh** [comment]
@mvolf @updateing You try reduce panel size on height?

**Comment by mvolf** [comment]
@varlesh If I reduce the panel height the icons turn to monochrome ones, but the panel and icons are too tiny then and the panel is hardly usable.
I'm using Plasma Display settings to set the scaling factor.
As I wrote in the first comment; Arc Plasma theme has two variants, as you can see in this screenshot:
https://i.postimg.cc/vBnKpvM3/arc.png

The Arc Color variant uses colours from colour scheme to determine the colour of the icons and uses the same icons independent of the panel/icon size. Maybe you can take a look how this was achieved in Arc Color theme and use the same approach. Just a suggestion, as this seems as best approach to me.

**Comment by varlesh** [comment]
@mvolf Please sent some full resolution screens with Materia and Arc Color also with tiny icons too...

**Comment by mvolf** [comment]
@varlesh Here you go:

**Comment by mvolf** [comment]
@varlesh Here you go:

Materia with "original" panel size:
<img width="960" alt="materia" src="https://user-images.githubusercontent.com/798213/52518226-9e33b600-2c47-11e9-8fb8-2966a6e89170.png">

Arc Color with the "original" panel size:
<img width="960" alt="arc_color" src="https://user-images.githubusercontent.com/798213/52518229-ac81d200-2c47-11e9-8b26-3dd25f763312.png">

Materia with tiny panel (this is the biggest panel size I can use to get monochrome icons):
<img width="960" alt="materia_tiny" src="https://user-images.githubusercontent.com/798213/52518240-e357e800-2c47-11e9-90dd-afaf891499f1.png">

I'm not sure if it's fully visible in screenshots, but the "tiny" panel is really to small on 4K monitors.

**Comment by varlesh** [comment]
@mvolf we found some info for fixed icon size on panel on [ArchWiki](https://wiki.archlinux.org/index.php/HiDPI#KDE). 
You can check this:
add option `PLASMA_USE_QT_SCALING=1` on **~.xprofile** > reboot PC

**Comment by mvolf** [comment]
@varlesh I can try that, but I frankly don't like that approach, since it's a hack and especially since I don't have the same issues with other themes.

**Comment by varlesh** [comment]
It's not hack, because KDE wrong worked with scale.

For all plasma themes i'm use 2 icon size:
22px - monochrome for panel
32px - colorized for notification/tooltip

For right work scale icons must be increased:
- 22px to 44px
- 32px to 64px

But really on KDE i'm see this:
- 22px  increased to 32px WHY?
- 32px increased (i don't know)

**Comment by varlesh** [comment]
Arc Color use ALL monochrome icons 22px and 32px too, but it's wrong way and kill my idea with colorized notification icons...
Arc Color created with support KDE Color Scheme.
But KDE Color Scheme not supported by Kvantum and i'm not seen reason doing this again.

Where used KDE Color Scheme:

- Plasma theme - yes
- Icons - yes
- Yakuake - no
- Kvantum - no
- Aurorae - no

**Comment by mvolf** [comment]
@varlesh Adding `PLASMA_USE_QT_SCALING=1` option didn't work for me, since I'm using 1 as a scaling factor anyway. I actually didn't change the scaling factor for any of the monitors. The only thing I changed is Forcing Font DPI to 144 (changing only this option makes works the best for me on 4K panels). That's why the suggested option does nothing for me. I have monochrome icons in 22px panel, but this panel size is simply to small for 4K monitors without scaling.

**Comment by varlesh** [comment]
@mvolf thx for testing. I'm soon add new version with monochrome icons only (with removed colorized)...
wait

**Comment by mvolf** [comment]
@varlesh That would be great! Thank you very much for your help and work you put in this :)

**Comment by varlesh** [comment]
But this icons will be on single size 22px - but i think it's not problem for hidpi and svg

**Comment by varlesh** [comment]
Please check it from git

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/52519102-de0e9380-2c6f-11e9-8a3c-173d57765565.png)

**Comment by mvolf** [comment]
@varlesh That's great thank you! I've verified that the Materia Mono works as expected now. I hope that it's not too much to ask; can you please create the Materia Blur Mono theme as well?

**Comment by varlesh** [comment]
@mvolf After some testing i'm added blur version.  Please sent screens with new mono version... I want check result

**Comment by mvolf** [comment]
@varlesh Here you go:
<img width="1920" alt="materia_mono" src="https://user-images.githubusercontent.com/798213/52519412-469f4580-2c5b-11e9-9281-66bd35294896.png">

**Comment by varlesh** [comment]
Icons blured :(
![image](https://user-images.githubusercontent.com/8083855/52519446-d3a2c880-2c74-11e9-83fc-cdc73101298d.png)

**Comment by varlesh** [comment]
See kdeconnect and media - blured

**Comment by mvolf** [comment]
Yes, they are blurred a bit, but it's not that bad as when you focus on it in screenshot. Of course, it would be great if that could be fixed, but it's OK even in this state.

**Comment by varlesh** [comment]
@mvolf Try change panel size for fix that...
All our icons have pixel perfect align:
![image](https://user-images.githubusercontent.com/8083855/52519477-401dc780-2c75-11e9-832b-9623534fd8fa.png)

**Comment by mvolf** [comment]
@varlesh Changing panel size doesn't do much for me. I'll play with it a bit more, but as seaid earlier, this blur is really not that visible for me.

**Comment by varlesh** [comment]
This don't like me, because our HIG it's Pixel Align. 
For compare:
![image](https://user-images.githubusercontent.com/8083855/52519549-15803e80-2c76-11e9-9752-32c76b8d0459.png)
![image](https://user-images.githubusercontent.com/8083855/52519550-1add8900-2c76-11e9-94ef-0667bae98f96.png)

**Comment by varlesh** [comment]
Mostly icons i can redraw for 32px monochrome.... but we have Network icons and this very long and hard:
![image](https://user-images.githubusercontent.com/8083855/52519598-f33af080-2c76-11e9-94d6-0f0fbbf27d9e.png)

**Comment by mvolf** [comment]
That's really not necessary if you ask me. Especially since that much work.

**Comment by varlesh** [comment]
I think need playing with scale option on KDE... it's best solution for us.
I'm not understand why KDE hardcoded 32px icon size for panel - it's very strange. For right work KDE must draw 22px as 44px, but really KDE draw 22px as 32px. It's a mystery for me

**Comment by mvolf** [comment]
@varlesh @SmartFinn Not sure if you guys are aware, but some of the latest changes broke bluetooth and kde connect tray icons for me (they're not monochrome, but full colour icons again):
<img width="146" alt="tray" src="https://user-images.githubusercontent.com/798213/52522645-6731c480-2c88-11e9-9c40-2d1fdddc384a.png">

P.S.
@varlesh Let me know once you have Materia Blur Mono for testing.

**Comment by SmartFinn** [comment]
@mvolf Materia Mono under development. It's too early for testing.

**Comment by mvolf** [comment]
@SmartFinn I know. I'm the one who reported this issue and was testing with @varlesh from the beginning. I was just notifying you about this in case you were not aware.

**Comment by varlesh** [comment]
@mvolf Use this version now:
https://github.com/PapirusDevelopmentTeam/materia-kde/tree/63006701300819e320a9f6f35e7074fe2247750a

**Comment by varlesh** [comment]
We port 22px icons to 32px...

**Comment by varlesh** [comment]
we soon add another branch for testing and retore commits...

**Comment by varlesh** [comment]
Sorry for that :)

**Comment by mvolf** [comment]
No worries :) Creating a feature branch is always a good idea ;)

**Comment by SmartFinn** [comment]
@mvolf reinstall the pack with the install.sh script to revert the recent changes.

**Comment by varlesh** [comment]
@mvolf We hack GitHub and purge wrong commits. Now all fine on Master branch :)

**Comment by mvolf** [comment]
@varlesh @SmartFinn Thanks guys. Build from master is now fine. Please keep me updated once you have something new on Mono/Mono Blur for testing.

**Comment by SmartFinn** [comment]
@mvolf it's time to test the updated Materia-Mono :wink:

**Comment by mvolf** [comment]
@SmartFinn Thanks for the update :) I'll create a build from master now and test it. I'll post a screenshot of tray icons once I install the new build.

**Comment by mvolf** [comment]
@SmartFinn @varlesh Tray icons now definitely look sharper to me. Slack and Franz icons are terrible, but that's to be expected.
Here's the screenshot (I didn't resize it on purpose, so you can see the full resolution):

<img width="1920" alt="mono_new" src="https://user-images.githubusercontent.com/798213/52713220-0a3f5280-2f97-11e9-9d5c-2687892bd1f5.png">

**Comment by mvolf** [comment]
@SmartFinn @varlesh Let me know once Mono Blur is ready for testing ;)

**Comment by mvolf** [comment]
@varlesh @SmartFinn I seems to me like the KDE Connect Icon is quite sharper than the rest of the icons (for example bluetooth and wifi). This could be due to the fact that KDE Connect icon doesn't have any curves. Just wanted to point this out to you guys.

**Comment by mvolf** [comment]
@varlesh @SmartFinn One more thing: Materia-Mono has monochrome icons in notifications/tooltips as well. I know that the initial idea was to have colour icons in notifications/tooltips and monochrome icons in tray.

**Comment by varlesh** [comment]
> @varlesh @SmartFinn I seems to me like the KDE Connect Icon is quite sharper than the rest of the icons (for example bluetooth and wifi). This could be due to the fact that KDE Connect icon doesn't have any curves. Just wanted to point this out to you guys.

@mvolf all fine (without hardcode-tray icons):
![image](https://user-images.githubusercontent.com/8083855/52764251-ad947400-3038-11e9-9429-4034e7d8d4e7.png)

> @varlesh @SmartFinn One more thing: Materia-Mono has monochrome icons in notifications/tooltips as well. I know that the initial idea was to have colour icons in notifications/tooltips and monochrome icons in tray.

Yes, Materia Mono now contained only monochrome icons

**Comment by varlesh** [comment]
@mvolf Some our icons have rounded corners...

**Comment by mvolf** [comment]
This is not related to your work, but just wanted to ask.
This is the best quality of icons I can get with hardcode-tray (slack and franz icons):
<img width="174" alt="tray" src="https://user-images.githubusercontent.com/798213/52769040-72da0e00-302f-11e9-86cd-7ff1493bc843.png">

Do you guys get better results? I used 16 for icon size and 2 as a scaling factor, so the resulting icon size is 32 (which should be fine since KDE uses 32 size for panel icons).

**Comment by mvolf** [comment]
@varlesh @SmartFinn I found no issues with Materia-Mono at all. Let me know once you manage to implement Materia-Mono Blur.

**Comment by varlesh** [comment]
@mvolf added

**Comment by mvolf** [comment]
@varlesh It looks great. Thanks!
