### ISSUE TITLE
Application menu button

### ISSUE THREAD

**Issue by BobbyWibowo** [PapirusDevelopmentTeam/materia-kde#37]
Application menu button in titlebar uses to the app's icon instead of a regular hamburger menu icon.
Here's how it looks with Materia KDE window decoration:
![Preview](https://i.fiery.me/oesI.png)

How it looks with Breeze window decoration:
![Preview](https://i.fiery.me/95bq.png)

I'm on Plasma 5.15.0.
It's not only limited to Dolphin. All other apps that supports the menu thingy will use their app icons instead.

**Comment by varlesh** [comment]
@BobbyWibowo i'm don't know application button ID for aurorae. And i think it's impossible:
https://techbase.kde.org/User:Mgraesslin/Aurorae#Buttons

**Comment by BobbyWibowo** [comment]
Huh yeah, apparently even in 2017 another theme creator stumbled upon this yet failed to find a solution: https://github.com/andreyorst/Breezemite/issues/5#issuecomment-301306097.

I also found this bug report: https://bugs.kde.org/show_bug.cgi?id=375862, however it appears to be pretty much abandoned or only half-solved (possibly due to the fact that no other users said anything more, lol).

Previously you couldn't even add application menu icon programmatically, but a fix was added soon after the report to solve that (as can be seen by how Plastik theme is doing it programmatically here, https://phabricator.kde.org/source/kwin/browse/master/plugins/kdecorations/aurorae/themes/plastik/code/plastikbutton.cpp$104).

This appears to be the file that will load themes, https://phabricator.kde.org/source/kwin/browse/master/plugins/kdecorations/aurorae/src/lib/auroraetheme.cpp$111, and if so, yeah, there is no line to load application menu icon at all.

**Comment by BobbyWibowo** [comment]
Anyway, the bug report I linked was already marked as resolved, so I created a new one, with more details: https://bugs.kde.org/show_bug.cgi?id=404322.

**Comment by varlesh** [comment]
You see, this not contained application menu icon now:
```
}
d->decorationPath = path;
 
// load the buttons
d->initButtonFrame(MinimizeButton);
d->initButtonFrame(MaximizeButton);
d->initButtonFrame(RestoreButton);
d->initButtonFrame(CloseButton);
d->initButtonFrame(AllDesktopsButton);
d->initButtonFrame(KeepAboveButton);
d->initButtonFrame(KeepBelowButton);
d->initButtonFrame(ShadeButton);
d->initButtonFrame(HelpButton);
 
d->themeConfig.load(config);
emit themeChanged();
}
```

**Comment by tusooa** [comment]
The upstream bug is fixed in https://invent.kde.org/plasma/kwin/-/commit/ca686f651a90f136ef887416fd318cc44624c356 .
