### ISSUE TITLE
Highlighted checkbox color

### ISSUE THREAD

**Issue by Goligoski** [PapirusDevelopmentTeam/materia-kde#41]
The checkbutton is undistinguished when highlighted. Looks fine on Adapta Dark.
Also, is there a way to increase a space between multiple checkbuttons?

![123](https://user-images.githubusercontent.com/16877709/53045913-7ccc9880-3497-11e9-8646-e0ace8458d57.png)

**Comment by varlesh** [comment]
this already updated on master branch
