### ISSUE TITLE
Incredibly dirty uninstall

### ISSUE THREAD

**Issue by ergcode** [PapirusDevelopmentTeam/materia-kde#42]
The script with the key to delete the theme does not work in the terminal.
`wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/materia-kde/master/install.sh | uninstall`
To execute it, you need to download the file and run it manually.
`wget https://raw.githubusercontent.com/PapirusDevelopmentTeam/materia-kde/master/install.sh && sh install.sh | uninstall`

After deleting the topic - hundreds of unnecessary files remain in the system.

The description has extremely few sample, what the theme looks like. This was the reason for the removal. It looks - awful, it seems that I installed Windows XP in a dark design.

**Comment by SmartFinn** [comment]
The correct command is 
`wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/materia-kde/master/install.sh | uninstall=true sh`

The command snippet in README has horizontal scrolling.

**Comment by varlesh** [comment]
@ergcode It's Windows XP?
![image](https://user-images.githubusercontent.com/8083855/53185197-f7bcbd00-3617-11e9-8c2c-c2e267794687.png)
