### ISSUE TITLE
Position of this blue line is not correct for the bottom panel

### ISSUE THREAD

**Issue by trmdi** [PapirusDevelopmentTeam/materia-kde#43]
Sorry, I don't know what the blue line is called.. When the panel is at the bottom of the screen:

Breeze:
![image](https://user-images.githubusercontent.com/11857205/54089321-6df04c00-439a-11e9-973d-f2bbb4d7490d.png)

Materia: 
![image](https://user-images.githubusercontent.com/11857205/54089338-88c2c080-439a-11e9-9b7f-a2f54b31affc.png)

**Expected**
- The blue line of Materia is on the top edge like it is in Breeze.

**Comment by varlesh** [comment]
fixed
