### ISSUE TITLE
Strange look after 20190319 release

### ISSUE THREAD

**Issue by ShaturIQ** [PapirusDevelopmentTeam/materia-kde#45]
It seems to me that the theme looks a bit strange after the 20190319 update. Is it normal?

Arch Linux
Plasma 5.15
Kvantum Manager 0.10.9

**Dolphin**
![Screenshot_20190320_213532](https://user-images.githubusercontent.com/47313424/54714520-c6bda280-4b59-11e9-9a9b-faec558a07c9.png)

**Kate:**
![Screenshot_20190320_213557](https://user-images.githubusercontent.com/47313424/54714527-cae9c000-4b59-11e9-965a-89225178c200.png)

**Settings:**
![Screenshot_20190320_213623](https://user-images.githubusercontent.com/47313424/54714535-cd4c1a00-4b59-11e9-9583-fda85419445d.png)

**Semi-selected checkboxes:**
![Screenshot_20190320_214416](https://user-images.githubusercontent.com/47313424/54714544-d0470a80-4b59-11e9-973e-f6d5bb444ad3.png)

**Comment by varlesh** [comment]
@ShaturIQ Что странного, то что фокус стал жирней? Так оно в GTK точно так же. Запустите `gtk3-widget-factory`  с последней версией Materia GTK с гита и сравните.
по поводу чекбокса, спасибо. исправлю

**Comment by varlesh** [comment]
по поводу фокуса на кнопках в Kate.... в дефолтной теме Kvantum тоже самое:
![image](https://user-images.githubusercontent.com/8083855/54735108-9576be00-4bbd-11e9-9036-79ed0df6ba24.png)

**Comment by varlesh** [comment]
чекбокс пофиксен.
По поводу фокуса, вот пример для наглядности с nautilus и `materia-gtk-theme-git_20190304`:
![image](https://user-images.githubusercontent.com/8083855/54735390-66614c00-4bbf-11e9-8414-1cc3c7cf9058.png)
![image](https://user-images.githubusercontent.com/8083855/54735425-9a3c7180-4bbf-11e9-9772-624d09c7f486.png)

**Comment by varlesh** [comment]
Фокус можно отключить на кнопках, но тогда будет не видно активную кнопку при работе с клавиатуры. 
Для этого следует добавить параметр `focusFrame=true` в секцию `[PanelButtonCommand]`. Так же можно его вырубить везде, удалив нужные слои из SVG или поставив прозрачность на 0%:

- focus-top
- focus-bottom
- focus-left
- focus-right
- focus-topleft
- focus-topright
- focus-bottomleft
- focus-bottomright

![image](https://user-images.githubusercontent.com/8083855/54735975-526b1980-4bc2-11e9-8c3b-dcbbca078a4c.png)
Но опять таки, повторюсь, при работе с клавиатурой это будет неудобно.
Другой вариант - это уменьшение толщины линии фокуса. Для этого следует поменять значения отрисовки:
```
[Focus]
inherits=PanelButtonCommand
frame=true
frame.element=focus
frame.top=1
frame.bottom=1
frame.left=1
frame.right=1
frame.patternsize=14
```

**Comment by ShaturIQ** [comment]
Да, Вы правы, без фокуса будет неудобно, просто линия какая-то уж очень бросская, ИМХО...

Особенно странно выглядит на кнопках, как по мне:

![Screenshot_20190321_112809](https://user-images.githubusercontent.com/47313424/54743553-15f0eb00-4bcd-11e9-97c0-1f6f55f3b9dc.png)

Или в списках:
![Screenshot_20190321_113026](https://user-images.githubusercontent.com/47313424/54743570-26a16100-4bcd-11e9-8333-909465ff646c.png)

**Comment by varlesh** [comment]
Ну я тут не при чем, так оно в апстриме gtk задумано. Мой пак представляет из себя, как можно ближе соответствовать оригиналу, для единого стиля.
Тем более я вам указал как уменьшить толщину линии, там и прозрачность можно подкрутить для себя...
