### ISSUE TITLE
Color Changed / Too Dark of Color for: theme.buttonFocusColor

### ISSUE THREAD

**Issue by rporter220** [PapirusDevelopmentTeam/materia-kde#47]
After upgrading to the 20190319 version, I noticed that the active indicators in latte-dock were barely able to be seen, but in the past they could easily been seen. I spoke with the creator of latte-dock and he stated that the active indicators are pulled from the plasma theme and utilize the `theme.buttonFocusColor` of the plasma theme.

To verify this was a recent change, I downgraded to the 20190117 version. In this version the active indicators are shown correctly, with a blue that is easily seen on the Materia background.

It appears that the color for `theme.buttonFocusColor` has changed between these to version to a very dark blue that is barely noticeable on the Materia background.

**Comment by varlesh** [comment]
fixed

**Comment by CreamyCookie** [comment]
When will this end up in the PPA? :)

**Comment by SmartFinn** [comment]
When we will create a release on GitHub. But you can update the package from [papirus-dev PPA](https://launchpad.net/~papirus/+archive/ubuntu/papirus-dev)

```
sudo add-apt-repository ppa:papirus/papirus-dev
sudo apt-get update
```

**Comment by CreamyCookie** [comment]
Will there be a release any time soon? If not that's totally okay, of course, I'd just rather not install another PPA.
