### ISSUE TITLE
The analog clock looks weird

### ISSUE THREAD

**Issue by trmdi** [PapirusDevelopmentTeam/materia-kde#48]
I'm not sure if the left one which has the length of the minute hand > the radius of the clock, is your design intention or not.
But there is definitely something wrong with the right one.

![image](https://user-images.githubusercontent.com/11857205/55047768-7e7e1300-5078-11e9-9224-a28fa944c2ee.png)

**Comment by varlesh** [comment]
Yes, it's design intention. With Papirus icons it's looks similar:
![image](https://user-images.githubusercontent.com/8083855/55050945-af584b00-506c-11e9-9f17-7890043083d0.png)
![image](https://user-images.githubusercontent.com/8083855/55051022-ea5a7e80-506c-11e9-86fa-5fb45f14418d.png)
As widet all worked fine... i try fix that for systemsettings

**Comment by varlesh** [comment]
@trmdi Fixed. Update from Git, clear cache and reapply theme:
`rm -rf ~/.cache/plasm* ~/.cache/icon*`

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/55054024-b46ec780-5077-11e9-9361-ad7782b4ad23.png)

**Comment by trmdi** [comment]
Well done. Thanks @varlesh !
