### ISSUE TITLE
Window Resizing is Very Laggy

### ISSUE THREAD

**Issue by delfianto** [PapirusDevelopmentTeam/materia-kde#49]
Environment:
- Manjaro Linux, kernel 5.0.5
- KDE Plasma 5.15.3
- Qt 5.12.2
- Mesa 19.0.1
- Radeon RX 550 GPU
- materia-kde-git 20190319.r3.g84823e2-1 (build from Aur)

What happened:
- When using the materia window decoration (both dark or light) resizing any application window will be very laggy.
- Switching back to the default window decoration (breeze) will make window resize buttery smooth again.

**Comment by varlesh** [comment]
It's specific on aurorae engine. I can't doing anything, aurorae vwey old engine((
