### ISSUE TITLE
Request: Add a shadow at the bottom of yakuake themes

### ISSUE THREAD

**Issue by Tichy** [PapirusDevelopmentTeam/materia-kde#5]
When using the dark theme, the colors of an opened yakuake and the underlying windows are the same, making them difficult to distinguish. I think this could be solved by adding a shadow on the lower border of the yakuake themes. I think that it would be consistent with the general material look.

This is how it looks with Materia Dark
![screenshot_20180419_180900](https://user-images.githubusercontent.com/2348771/39004362-6daa5b8e-43fd-11e8-946e-8efcf0723b83.png)

The Breeze perfect dark theme for yakuake has a shadow, and in a similar situation, looks like this. Beside the different shade of gray, the shadow makes the yakuake window more distinguishable.
![screenshot_20180419_181031](https://user-images.githubusercontent.com/2348771/39004442-9a5c1f46-43fd-11e8-9020-3dcc682a2e5e.png)

**Comment by varlesh** [comment]
first versions yakuake KF5 have bad support alpha-channel... i try it

**Comment by varlesh** [comment]
updated https://github.com/PapirusDevelopmentTeam/materia-kde/commit/6b534a68b6d17d8c8de7d41f560027d5beebc609

**Comment by k1nghat** [comment]
can you add the same shadow styling to yakuake like the rest of the materia windows have? specifically the left and right sides so you can make out the yakuake window. you can see the dolphin left/right border shadows behind the yakuake window.

![image](https://user-images.githubusercontent.com/16073360/52972898-e9557380-3381-11e9-80a8-186e5ab382d7.png)

**Comment by varlesh** [comment]
It's imposssible. Yakauke draw only Title and Tabs.
> also, is this yakuake theme not in the repo anymore or should it be downloaded manually from here?:
https://store.kde.org/p/1229144/

Why not?
https://github.com/PapirusDevelopmentTeam/materia-kde/tree/master/yakuake/skins/materia-dark

**Comment by k1nghat** [comment]
> > also, is this yakuake theme not in the repo anymore or should it be downloaded manually from here?:
> > https://store.kde.org/p/1229144/
> 
> Why not?
> https://github.com/PapirusDevelopmentTeam/materia-kde/tree/master/yakuake/skins/materia-dark

ah ok. so its part of the `materia-kde` install and is automagically installed on yakuake.

is there a place where you style guys chat? im having an issue where i dont get the resize cursor for dolphin but do on other windows.
