### ISSUE TITLE
Selection of desktop items are barely visible

### ISSUE THREAD

**Issue by CreamyCookie** [PapirusDevelopmentTeam/materia-kde#50]
Unless I'm missing something, the selection background color was much more visible (less transparent) previously .

Now I can just barely make it out.

![Untitled](https://user-images.githubusercontent.com/3063858/57647814-413bf900-75c4-11e9-93b4-6ed35149a26f.png)

**Comment by varlesh** [comment]
fixed

**Comment by CreamyCookie** [comment]
Awesome, thank you! :)
