### ISSUE TITLE
Mention copr for fedora users

### ISSUE THREAD

**Issue by memeplex** [PapirusDevelopmentTeam/materia-kde#51]
Recently I've requested Laurent Trequier to add a package for materia kde to his copr (which also includes materia gtk) which he kindly and promptly did. Maybe you would like to add his copr https://copr.fedorainfracloud.org/coprs/tcg/themes to your list of installation alternatives.

**Comment by varlesh** [comment]
No problem. But Gtk theme failed build:
![image](https://user-images.githubusercontent.com/8083855/58250313-2f034d00-7d72-11e9-874d-2622af9dffdd.png)

https://copr.fedorainfracloud.org/coprs/tcg/themes/packages/

**Comment by varlesh** [comment]
added, thx ))

**Comment by memeplex** [comment]
It fails just for some architecture that I can't remember now. It's not as important as the red color might suggest :)
