### ISSUE TITLE
blank line between top bar and window on kde 5.16 beta

### ISSUE THREAD

**Issue by fusco2k** [PapirusDevelopmentTeam/materia-kde#52]
There is a blank line between the kde top menu bar and the active maximized window (this case Chromium). Since I'm on beta I don't know if the issue replicate on Stable. Using Arch Linux.

![image](https://user-images.githubusercontent.com/49331640/58386990-11d2b680-7fde-11e9-8220-82d4b28e02b2.png)

**Comment by varlesh** [comment]
Maybe it's problem with your Aurorae theme? How this looked with Materia Aurorae and Breee decoration?

**Comment by fusco2k** [comment]
Looks like is something with the plasma theme. When I set the look and feel/window decorations to Materia and Plasma to something else line Breeze or Numix fixes it. If I set back the plasma to Materia the bug reappears.

![image](https://user-images.githubusercontent.com/49331640/58415394-b394ea80-8054-11e9-837e-45ecfe6df384.png)

This one is setting Plasma to Numix and the rest to Materia.

**Comment by fusco2k** [comment]
The search dock is affected too. The first image is pure Materia, the second one is using Numix
![image](https://user-images.githubusercontent.com/49331640/58415523-1edebc80-8055-11e9-93b6-d9dcc029696c.png)
![image](https://user-images.githubusercontent.com/49331640/58415551-2f8f3280-8055-11e9-8541-52f8c700d86e.png)

**Comment by varlesh** [comment]
@fusco2k possible fixed, please check it. Update theme from Git, remove cache and restart plasma:
`killall plasmashell && rm -rf ~/.cache/plasm* ~/.cache/ico*`
**ALT+F2** > `plasmashell`

**Comment by fusco2k** [comment]
Now it's perfect. Thanks for the quickly response and fix.
