### ISSUE TITLE
Toolbar button hover is off center

### ISSUE THREAD

**Issue by inkubux** [PapirusDevelopmentTeam/materia-kde#53]
When hovering a toolbar button the icon is off center 

I'm using the dev PPA on kubuntu with kvantum

I love the Materia blur theme and without this little detail it would be perfect :)

![materia-toolbat-off-center](https://user-images.githubusercontent.com/342110/58523094-2a370280-8191-11e9-8366-43eb1adb3b35.png)
![Screenshot_20190528_214414]

here is my pc infos:

![nodefetch](https://user-images.githubusercontent.com/342110/58523336-163fd080-8192-11e9-8214-5b1f40e7dcf0.png)

Thanks a lot for your help

**Comment by varlesh** [comment]
This happened because on some buttons used arrow. For example, Kvantum Default theme:
![image](https://user-images.githubusercontent.com/8083855/58529617-a3177800-81ec-11e9-90cf-2cfd3fb252bf.png)
But i'm disable this arrow and this not worked very good:
```
[PanelButtonTool]
indicator.element=arrow
indicator.size=0
```

**Comment by r0skar** [comment]
Experiencing the same issue. Is it possible to completely disable the "hover" effect?

**Comment by ashahir05** [comment]
Same issue here. Would be nice if you  disabled the hover effect as said by @r0skar . Anyways, I will open an issue on tsujan/kvantum to see if he can come up with a way to disable it.

**Comment by ashahir05** [comment]
@varlesh Just to let you know, according to tsujan, all Kvantum theme needs to come with a arrow. Don't really know if you have put it in.

**Comment by varlesh** [comment]
Yes, it's my decision for design. But you can change indicator size. For example, set 8:
```
[PanelButtonTool]
indicator.element=arrow
indicator.size=8
```

**Comment by ashahir05** [comment]
Yeah I did that and it was centered. Another thing you did:
`[PanelButtonCommand]
frame.top=6
frame.bottom=10`
But that makes the text as though it is a bit above on the button. So I changed it to:
`[PanelButtonCommand]
frame.top=6
frame.bottom=6`
Which made the buttons on the bar that you get when clicking on search button totally messed up.
However:
`[PanelButtonCommand]
frame.top=7
frame.bottom=7`
Seems to be all good. All buttons are fine and centered.

**Comment by varlesh** [comment]
updated

**Comment by varlesh** [comment]
arrow enabled too

**Comment by ashahir05** [comment]
@varlesh Use:
```
[PanelButtonCommand]
frame.top=8
frame.bottom=8
```
instead.

Using 7 will break the cross button as shown here:
![image](https://user-images.githubusercontent.com/44367115/70033147-0ee1ff80-15d9-11ea-8e47-f1d1ed3deb04.png)

**Comment by varlesh** [comment]
this already fixed. see commits:
https://github.com/PapirusDevelopmentTeam/materia-kde/commit/842f23b40a4ca73e2664d71eb2b283ce9e90e4c3

**Comment by tsujan** [comment]
@varlesh 

I removed arrows from tool-buttons that have "instant popups" (`QToolButton::InstantPopup`), by commenting out them in the code: https://github.com/PapirusDevelopmentTeam/materia-kde/commit/842f23b40a4ca73e2664d71eb2b283ce9e90e4c3

This is an example in Dolphin (with KvMojave):

![instant_popup](https://user-images.githubusercontent.com/981076/70041788-04bd0280-15d3-11ea-8c36-e9e3950056dc.png)

Please note that other kinds of menu tool-buttons have arrows, as they should. The arrows should not be disabled in the theme.

A side note:

I saw these lines in your (beautiful) theme:
```
frame.top=8
frame.bottom=8
frame.left=8
frame.right=8
```
A suggestion: You could set them to 3 and use `frame.expansion` instead. Most themes that are included in Kvantum use `frame.expansion` but see `KvGnome` for an example. That may be a little complex but will be worth the effort because exceptions (= bad app codes) will be handled better.

**Comment by tsujan** [comment]
Oh, I gave the incorrect commit address in the above comment! Corrected it now.

**Comment by varlesh** [comment]
@tsujan Perfect. Big thx!!! :+1:

**Comment by varlesh** [comment]
> Please note that other kinds of menu tool-buttons have arrows, as they should. The arrows should not be disabled in the theme.

It's ok. For toolbar i'm use another element

**Comment by tsujan** [comment]
@varlesh Now it's like Breeze, not like Fusion. Breeze doesn't draw an arrow with `QToolButton::InstantPopup` but draws it in other cases.

Your theme and this discussion made me revise my old decision about drawing tool-button arrows -- after a little hesitation. Now I think the Breeze way is better; hence the change :) So, I'm the one who should thank you for the idea and also @ashahir05 for opening https://github.com/tsujan/Kvantum/issues/462.

**Comment by varlesh** [comment]
about `frame.expansion` i know about that, but this not worked for my buttons... And i don't know why

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/70049474-35f2fe00-15e6-11ea-9c89-734cbea1bfb0.png)
```
[PanelButtonCommand]
frame=true
frame.element=button
frame.top=3
frame.bottom=3
frame.left=3
frame.right=3
interior=true
interior.element=button
indicator.size=8
text.normal.color=#dfdfdf
text.focus.color=white
text.press.color=#dfdfdf
text.toggle.color=white
text.shadow=0
text.margin=1
text.iconspacing=4
indicator.element=arrow
text.margin.top=2
text.margin.bottom=2
text.margin.left=2
text.margin.right=2
frame.expansion=12
```

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/70049578-676bc980-15e6-11ea-8663-eaeaf698c1b9.png)
```
[PanelButtonCommand]
frame=true
frame.element=button
frame.top=8
frame.bottom=8
frame.left=8
frame.right=8
interior=true
interior.element=button
indicator.size=8
text.normal.color=#dfdfdf
text.focus.color=white
text.press.color=#dfdfdf
text.toggle.color=white
text.shadow=0
text.margin=1
text.iconspacing=4
indicator.element=arrow
text.margin.top=2
text.margin.bottom=3
text.margin.left=2
text.margin.right=2
frame.expansion=0
```

**Comment by varlesh** [comment]
Maybe it's happened because used long shadows/borders for buttons... i don't know... but i can't find frame.expantion config for this buttons with better looking.
Sorry for my English))

**Comment by tsujan** [comment]
@varlesh Your theme is OK -- `frame.expansion` was just a suggestion because of round hover effect in your theme; otherwise, there's no need to it here.

If I find the time, I'll add `frame.expansion` to your theme (in a PR). Unfortunately, my free time is taken by several projects for now.

**Comment by varlesh** [comment]
@tsujan Don't worry, now this worked as conceived

**Comment by tsujan** [comment]
@varlesh  `frame.expansion` can be very tricky. Don't damage your theme for it; your theme is really good as it is.

**Comment by varlesh** [comment]
@inkubux @r0skar @ashahir05 Materia Dark with Kvantum 0.13:
![image](https://user-images.githubusercontent.com/8083855/70241137-fb28cb80-1787-11ea-9030-ac0997f4bb8c.png)
@tsujan worked fine. Thx ))

**Comment by ashahir05** [comment]
Thanks! Looks pretty darn good now!
