### ISSUE TITLE
Aurorae theme has square black corners at the top and the bottom of windows.

### ISSUE THREAD

**Issue by freefreeno** [PapirusDevelopmentTeam/materia-kde#55]
On the new Plasma 5.16 the aurorae theme has little square black tip corners sticking from the theme on top corners and bottom corners of windows.

**Comment by varlesh** [comment]
Not confirm this:
![image](https://user-images.githubusercontent.com/8083855/59482795-6d74bf00-8e7b-11e9-8d85-6489c46d845b.png)
Try remove cache:
`rm -rf ~/.cache/plasm* ~/.cache/ico*`
and restart plasma session
Also check effects, maybe need disable blur

**Comment by varlesh** [comment]
NOTE: Aurorae - it's very old decoration engine and kde devs don't want support or update this.
Now mostly KDE apps use QML and this don't like me, because QML styles hardcoded and not customized... It's very sad
For example:
- Breeze decoration
- Muon Discover
- Elisa Player
- Babe Player
- System Settings (side panel mode)
and etc...

**Comment by freefreeno** [comment]
![Screenshot_20190614_005921](https://user-images.githubusercontent.com/41884680/59486675-beff5880-8e3f-11e9-8de4-d053cd390112.png)


This is new install. Never had a theme installed. This was the first one. It wasn't doing this before update but it does have black tips at corners for sure. I restarted and cleared cache.

**Comment by varlesh** [comment]
https://bugs.kde.org/show_bug.cgi?id=395725
Disable blur on effects.

**Comment by freefreeno** [comment]
@varlesh  I have a question. Sorry to bother. Is there a reason you do not use svgz???? If so what is the reason. Thanks in advance.

**Comment by SmartFinn** [comment]
@freefreeno no reason to gzipping the SVG files. We optimize the SVG files with SVGO and using sed for development. SVGZ format makes using the tools more difficult.

**Comment by freefreeno** [comment]
Ok thanks. Well I see everyone doing it but I didn't know it it had a upside besides just being smaller. Thanks

**Comment by freefreeno** [comment]
@varlesh  I just also found a problem. The window decorations do not apply when selecting materia-dark look and feel and it is because you have it this way. Everything does correctly but the aurorae.

[kwinrc][org.kde.kdecoration2]
theme=__aurorae__svg__Materia-Dark

It has to be this way to work or this is the case on my Plasma 5.16.

[kwinrc][org.kde.kdecoration2]
library=org.kde.kwin.aurorae
theme=__aurorae__svg__Materia-Dark

**Comment by varlesh** [comment]
Thx for info, added https://github.com/PapirusDevelopmentTeam/materia-kde/commit/dfdbdde3324551c4439f69748600df2505a761f4

**Comment by varlesh** [comment]
> I would like to make my own widgets and i do not even know where to begin but I guess if i search enough I will figure it out. 

Widgets draw from plasma theme:
`/usr/share/plasma/desktoptheme/THEMEwidgets/`
I think you need read this tutorial:
https://techbase.kde.org/Development/Tutorials/Plasma5

> By the way why is the right click menu so light when using Kvantum to apply the theme?
- Materia use dark titlebar only and light other elements
- Materia Light use all light elements
- Materia Dark use all dark elements

Our pack created  for compatibility with [GTK Theme](https://github.com/nana-4/materia-theme)

**Comment by freefreeno** [comment]
@varlesh Exactly. Materia dark has light right click menus on my PC while using Kvantum. If I could get the answer to my last question please I will leave you alone. If you set kvantum as widget in defaults look and feel file for people without kvantum will it fall back to breeze. If not then people without kvantum will have problems.

**Comment by varlesh** [comment]
@freefreeno 
>Exactly. Materia dark has light right click menus on my PC while using Kvantum.

I don't know why. Maybe you use Materia (but not Materia Dark?)
![image](https://user-images.githubusercontent.com/8083855/59568014-ee9fa200-9085-11e9-8307-4c5deef92b2d.png)
> If you set kvantum as widget in defaults look and feel file for people without kvantum will it fall back to breeze. If not then people without kvantum will have problems. You have this.

This not solve problem if Kvantum not installed, but on readme we write about that:
![image](https://user-images.githubusercontent.com/8083855/59567981-586b7c00-9085-11e9-8b5b-31530ae82f72.png)

Kvantum not available on more distos and we write about that - INSTALL KVANTUM engine.
 It's GREAT engine for me))

**Comment by freefreeno** [comment]
@varlesh Ok I guess that light color is just the color and I do have Kvantum installed. I am on Arch I stii want to know the answer the the question though........

If I set kvantum in my look and feels like you have it as default widget like this is it gonna mess people without kvantum up???

[kdeglobals][KDE]
widgetStyle=kvantum

or does it just use breeze if kvantum is not available?????

**Comment by varlesh** [comment]
> or does it just use breeze if kvantum is not available?????

Yes if kvantum not installed, used breeze.

**Comment by varlesh** [comment]
Compare Kavntum vs Breeze.
**Kvantum vs GTK**
![image](https://user-images.githubusercontent.com/8083855/59578397-18ce7f80-90d9-11e9-9859-5047ed78d9a7.png)
**Breeze vs GTK**
![image](https://user-images.githubusercontent.com/8083855/59578448-49aeb480-90d9-11e9-8ff2-7807ebaea293.png)

**Comment by openmindead** [comment]
I had to revamp Materia Aurorae decorations in order to get rid of these ugly corners, you can find it on [pling](https://www.pling.com/p/1270259/) as Materia-Breath_aurorae. Feel free to use @varlesh
