### ISSUE TITLE
Plasma theme is broken from last update

### ISSUE THREAD

**Issue by psifidotos** [PapirusDevelopmentTeam/materia-kde#56]
During last update you have probably removed the "shadow-center" element from panel-background .svg file

This element is **VERY** important because all the CENTER elements are used in order for Plasma to identify if the general element exists.

Example "shadow" element:
1. a program requests the "shadow" element from "panel-background"
2. Plasma checks if the svg file contains "shadow-center"
3. If "shadow-center" does not exist then plasma thinks that "shadow" IS NOT PRESENT

"shadow-center" can be just a fully transparent element

Issues:
Probably from last update if you go to plasma systemsettings->plasma themes then for Materia you may notice that it does not have shadows at all

**Comment by varlesh** [comment]
Thx for info, fixed https://github.com/PapirusDevelopmentTeam/materia-kde/commit/017ef4f8560a46bb689da9cddafb01d5da985186

**Comment by varlesh** [comment]
@psifidotos Hi Michail. i know you good developer and very good know QML/Qt/Plasma and other tools...
Maybe you know how inject QML style for one Plasma widget on Plasma theme.
For example, KickOff widget - i hate this lines under TabBar it's possible hack?
![image](https://user-images.githubusercontent.com/8083855/59582399-33a8f000-90e9-11e9-8fa7-4e12ef17fb9d.png)
On code used Text color but i'm want hide this or recolor this lines (separator):
```
Header {
        id: header
    }

    Rectangle {
        id: headerSeparator

        height: Math.floor(units.devicePixelRatio)
        color: theme.textColor
        opacity: 0.2
        width: root.width - 2 * units.gridUnit

        anchors {
            top: header.top
            horizontalCenter: header.horizontalCenter
        }
    }
```

**Comment by psifidotos** [comment]
Only for your computer? 

I know how to recolor that item and the change would take place only in your computer but I don't know if it is possible to distribute this to other users

**Comment by varlesh** [comment]
@psifidotos No, i mean injection QML on Plasma Theme. It's possible? 
Yes i  know, i can modify original widget and hide this separators... only set `opacity: 0` but this impossible for other users out the box

**Comment by psifidotos** [comment]
> @psifidotos No, i mean injection QML on Plasma Theme. It's possible?
> Yes i know, i can modify original widget and hide this separators... only set `opacity: 0` but this impossible for other users out the box

sorry I dont know, the best to answer this I think is the kvantum developer

**Comment by varlesh** [comment]
@psifidotos Ok, thx
