### ISSUE TITLE
After the latest update kickoff menu has small black tip at top right corner 

### ISSUE THREAD

**Issue by freefreeno** [PapirusDevelopmentTeam/materia-kde#57]
After today's update I am seeing a small black tip at the top right hand corner of kickoff menu.
It is small but it is there even on restart and clean the cache.
![Screenshot_20190616_200816](https://user-images.githubusercontent.com/41884680/59572417-ba6eb600-9072-11e9-86f7-fdced84c83a4.png)

**Comment by varlesh** [comment]
i'm not update aurorae decoration

**Comment by varlesh** [comment]
I'm not see this
![image](https://user-images.githubusercontent.com/8083855/59578262-6eeef300-90d8-11e9-98d2-94cc80b65adf.png)

**Comment by freefreeno** [comment]
Well it is there. If a person enables blur any at all there is black tips on nearly every corner. As soon asI disable blur they are gone
