### ISSUE TITLE
Materia Blur does not blur all windows

### ISSUE THREAD

**Issue by ericleman** [PapirusDevelopmentTeam/materia-kde#58]
I am using the Materia Blur theme with Kvantum. It is great. However, for some windows, it does not blur. See in the attached picture, the "About System" windows from KDE is transparent but not blurred, which is painful sometimes (see 2nd pictures)

![image](https://user-images.githubusercontent.com/26767717/60732228-c9e27000-9f49-11e9-9df2-e9d17f464e2c.png)

![image](https://user-images.githubusercontent.com/26767717/60732385-2c3b7080-9f4a-11e9-9bbb-6e5d71f49dad.png)

**Comment by varlesh** [comment]
Kvantum not draw blur effect on Plasma WS, it's Kwin option... Check it on Breeze engine

**Comment by varlesh** [comment]
Worked:
![image](https://user-images.githubusercontent.com/8083855/67118987-2c106980-f1f7-11e9-921d-a3eaf676a8b9.png)
Plasma 5.17
Kvantum 0.12.1+repack-1~bionic1
