### ISSUE TITLE
Question.... Is it safe to run plasma svg's thru svgo like the script for papirus icons ??

### ISSUE THREAD

**Issue by freefreeno** [PapirusDevelopmentTeam/materia-kde#59]
Just wondering if it is safe to use svgo at Papirus icons on plasma svg's.

**Comment by SmartFinn** [comment]
Yep. We using it from time to time.

**Comment by freefreeno** [comment]
@SmartFinn That is a really cool script. It fixed some icons for me yesterday so I applaud that sure. I had some that would not change colors on PC but would change inside inkscape.
