### ISSUE TITLE
Blur Theme: Ksysguard graph glitches

### ISSUE THREAD

**Issue by dotWAVE** [PapirusDevelopmentTeam/materia-kde#60]
![Screenshot_20190714_201403](https://user-images.githubusercontent.com/2576219/61191126-791ef580-a674-11e9-994c-875287cb4878.png)
This only occurs with the blur theme, all other materia themes behave normally.

**Comment by varlesh** [comment]
I know about this bug... BUT it does not always reproduced.
![image](https://user-images.githubusercontent.com/8083855/61193579-47864880-a6cd-11e9-8ec2-66ac9be99639.png)

**Comment by varlesh** [comment]
Try it on other transparent themes for Kvantum, for example **KvMojave**

**Comment by dotWAVE** [comment]
I do not have a KvMojave theme, however to test I installed https://github.com/Luwx/Mojave-kvantum and the graphs look fine.

**Comment by dotWAVE** [comment]
Something of note, the area behind the graph in your screenshot is opaque, and mine is transparant.

**Comment by dotWAVE** [comment]
Updating kvantum to 0.11.3 fixes the bug
![Screenshot_20190901_230527](https://user-images.githubusercontent.com/2576219/64087946-288b5680-cd0d-11e9-954e-53a98aa82b8a.png)
