### ISSUE TITLE
Blur does not available on taskbar using materia blur

### ISSUE THREAD

**Issue by mathpfvr** [PapirusDevelopmentTeam/materia-kde#61]
![Screenshot_20190723_142305](https://user-images.githubusercontent.com/7264001/61733303-df330900-ad55-11e9-8ad5-c473e0e3f87f.png)

The blur effect does not work on the materia blur theme, please add the effect on the theme

**Comment by varlesh** [comment]
@mathpfvr Hi. It's Our style. Blur and opacity not applied on window decoration + toolbar and panel on plasmashell.
![image](https://user-images.githubusercontent.com/8083855/61764223-78f7c600-ade9-11e9-89b7-03007f679daa.png)
But you can change this manually on  `widgets/panel-background.svg`
