### ISSUE TITLE
Follow Breeze Window instead of crappy Kvantum/default

### ISSUE THREAD

**Issue by FadeMind** [PapirusDevelopmentTeam/materia-kde#62]
@varlesh hi. You made great work with Materia. Thanks. Sadly Kvantum 3D effects/shadows did not looking fine with flat Mono Papirus themes.
Could you consider adopt Window from Breeze against Kvantuam?
![Screenshot_20190813_103951](https://user-images.githubusercontent.com/9846948/62927402-c1861c00-bdb6-11e9-890f-18c84bba44e8.png)
IMHO color matching is better that Materia Window default and Kvantum. 
For comparing. Default Materia KDE settings + Kvantum 
![Screenshot_20190813_104639](https://user-images.githubusercontent.com/9846948/62927899-bda6c980-bdb7-11e9-99b4-81c8e49c8275.png)

I missed something?

Regards

**Comment by varlesh** [comment]
@FadeMind Hi. Maybe you mean Aurorae decoration and Breeze decoration?

**Comment by FadeMind** [comment]
@varlesh sorry for mess up. I did not read fully README

> Recommendations
> For better looking please use this pack with Kvantum engine.
> 
> Run kvantummanager to choose and apply Materia's theme.

aaand works :wink: 

![Screenshot_20190813_134115](https://user-images.githubusercontent.com/9846948/62938956-69f4aa00-bdd0-11e9-9c84-309416140fd4.png)
![Screenshot_20190813_134333](https://user-images.githubusercontent.com/9846948/62938958-6a8d4080-bdd0-11e9-891d-9b27bdeed604.png)

Regards
