### ISSUE TITLE
MateriaBlur clashing colors

### ISSUE THREAD

**Issue by dotWAVE** [PapirusDevelopmentTeam/materia-kde#63]
The blur theme has strange color behavior most easly seen in the networkmanager system settings module. This is how it displays with MateriaBlur:
![Screenshot_20190901_231005](https://user-images.githubusercontent.com/2576219/64088122-ff1efa80-cd0d-11e9-813f-033cc4f823a6.png)
And this is how it displays with MateriaDark:
![Screenshot_20190901_231330](https://user-images.githubusercontent.com/2576219/64088144-1e1d8c80-cd0e-11e9-978b-0e9afc42a596.png)
Also of note is the black line around some content on the MateriaDark theme, though the lefthand menu appears to display the correct color.

Kvantum version 0.11.3

**Comment by varlesh** [comment]
It's bug draw alpha channel on **base.color**. We use `base.color=#30303082`
 I think it's injection QML module on Qt (recent times more modules and apps KDE devs port to QML )
I can remove alpha channel for fix that, but we lost opacity on window:
![image](https://user-images.githubusercontent.com/8083855/64223995-f897ab00-cee6-11e9-988e-ca427f07a201.png)

**Comment by varlesh** [comment]
`kcm_networkmanagement`:
https://github.com/KDE/plasma-nm/tree/master/kcm/qml
https://github.com/tsujan/Kvantum/issues/333

**Comment by dotWAVE** [comment]
Yea, QML is pretty crap. Use any theme that isn't breeze and it's plain to see. Does the entire window lose translucency or just the inside frame? What do I have to edit to test this?

**Comment by varlesh** [comment]
You can change `base.color=#30303082` to `base.color=#303030`
For example, open Materia config file - run Dolphin (and not close it). Change `base.color` and save document. Run another copy Dolphin and see different.

**Comment by dotWAVE** [comment]
that will make all windows opaque, no?

**Comment by varlesh** [comment]
Yes, all windows. You can check it with any  Qt-application (nonQML)

**Comment by dotWAVE** [comment]
looks like the best solution for now is just to force just that application to use MateriaDark in kvantummanager. Closing because the bug belongs to a different project.
