### ISSUE TITLE
Is it possible to bypass blur effect in Konsole (or any other specific apps)?

### ISSUE THREAD

**Issue by Frederick888** [PapirusDevelopmentTeam/materia-kde#64]
Personally I think it's nice to be able to read docs beneath the terminal.

Currently although I have unchecked 'Blur background' in Konsole -> Profile -> Appearance -> Colour scheme & fonts -> Edit, it's still blurred by default unless I open a new tab/change colour scheme/etc.

**Comment by varlesh** [comment]
If Konsole window not transparented - blur not applied.
You can change opacity on Konsole Profile Color Scheme:
![image](https://user-images.githubusercontent.com/8083855/67118208-7b559a80-f1f5-11e9-84ad-24b8b2ff4b5a.png)

**Comment by Frederick888** [comment]
I mentioned that the reason why I want it to stay transparent was to see docs beneath lol...

Anyway, I'll report it to Kvantum if it's their issue.

PS: Someone also opened a ticket at https://bugs.kde.org/show_bug.cgi?id=410677
