### ISSUE TITLE
Minimum width of input box in Spectacle isn't respected

### ISSUE THREAD

**Issue by Frederick888** [PapirusDevelopmentTeam/materia-kde#65]
I originally posted this to KDE bug tracker https://bugs.kde.org/show_bug.cgi?id=411577 but was told this was a downstream issue. Sorry if it's actually a Kvantum problem.

The delay input box has got a minimum 160px setting but it's not respected when Materia is used. The width of the box grows once I click '+' which is slightly annoying cos my second click will hit '-'.

Screenshot - before click
![image](https://user-images.githubusercontent.com/4507647/65400836-d3240000-de07-11e9-9c48-d4e5aca4df3b.png)
Screenshot - after click
![image](https://user-images.githubusercontent.com/4507647/65400838-d6b78700-de07-11e9-855a-38a8466f11be.png)

**Comment by varlesh** [comment]
It's not Materia bug. Reproduced on default Kvantum theme too. Please report to Kvantum developer
