### ISSUE TITLE
Use a valid plugin name to allow installing Plasma themes from SystemSettings

### ISSUE THREAD

**Issue by trmdi** [PapirusDevelopmentTeam/materia-kde#67]
https://github.com/PapirusDevelopmentTeam/materia-kde/blob/58fc59f0226ec41dad08190e904725ba25941e62/plasma/desktoptheme/Materia-Blur/metadata.desktop#L6

If you install it with the `kpackagetool5 -i . -t Plasma/Theme` it will say that name is invalid. Try removing the space character to make it valid.
I guess this is the reason why I can't install Materia Blur from Systemsettings > Get Plasma theme...

**Comment by varlesh** [comment]
Thx for report. Fixed with -
