### ISSUE TITLE
[feature] - Materia Theme with bigger roundness

### ISSUE THREAD

**Issue by psifidotos** [PapirusDevelopmentTeam/materia-kde#71]
@varlesh hello, I am answering too many threads from plasma users requesting bigger rounded corners and shadows from Latte... I am trying to explain them that this is possible but from plasma theme side. Whatever roundness and shadows the plasma theme is supporting, same roundness and shadows Latte is also providing...

I love Materia plasma theme and I use it in my system. Is it possible to create an alternative plasma theme with bigger roundness and shadows? It would help a lot the community to understand the concept and also try to emulate it afterwards with other color palettes... 

Latte is discovering the current Materia panel background roundness to 4pixels... A new theme with roundness >10 would be more than appreciated even for just demonstration purposes...

example roundness from Deepin: https://149366088.v2.pressablecdn.com/wp-content/uploads/2019/10/deepin-v20-apps.jpg

**Comment by varlesh** [comment]
@psifidotos Hi. Angle is a quarter circle. I can make more rounded angles, BUT not more quarter circle.
For example:
![image](https://user-images.githubusercontent.com/8083855/71546454-685b0580-29b0-11ea-99a3-503493ae3624.png)
You can test it with updated panel-background widget:
[panel-background.tar.gz](https://github.com/PapirusDevelopmentTeam/materia-kde/files/4007212/panel-background.tar.gz)

**Comment by psifidotos** [comment]
unfortunately that gives 5 pixels. that is only +1 pixel..

you mean that 5 pixels roundness is the maximum roundness that plasma can provide??

**Comment by varlesh** [comment]
I think better doing this programmatically, because plasma draw panel from 9 elements (top, topleft, right and etc). But Gnome like DE's doing this from one element. I don't know how draw rounded angle more than quarter circle.
Also maybe you help method from Kvantum engine - used `frame.expansion` for rounded square elements (on cpp and qt5)

**Comment by psifidotos** [comment]
I believe plasma devs are not aware of the issue, I have opened a task to be discussed, https://phabricator.kde.org/T12442

**Comment by psifidotos** [comment]
managed to do it... I just had to make them bigger in the panel-background svg file... of course it would like adjustments for the margins...

![Screenshot_20191228_234912](https://user-images.githubusercontent.com/2216474/71549828-d01f4980-29cc-11ea-84b3-59da72cfd917.png)

**Comment by varlesh** [comment]
@psifidotos hm, it's worked yes. And this strange for me, because i'm doing only scale x2 and not understand that
![image](https://user-images.githubusercontent.com/8083855/71552879-29639900-2a1e-11ea-936f-2f7e14809cfa.png)

**Comment by psifidotos** [comment]
Only thing needs fixing is that shadows must become smaller in thickness and margins probably need to be Increased

**Comment by psifidotos** [comment]
@varlesh we need one such plasma theme well presented. Kde store does not have any such plasma theme and kde users do not think that it is possible

**Comment by varlesh** [comment]
@psifidotos i'm create soon new plasma theme... but after holidays.
It's example fixed panel-background:
[panel-background.tar.gz](https://github.com/PapirusDevelopmentTeam/materia-kde/files/4009887/panel-background.tar.gz)

**Comment by psifidotos** [comment]
so happy to hear!! :) it will help the kde community a lot!!! :)

**Comment by varlesh** [comment]
Theme maked... based on Breeze style (without KDE Color scheme support now).
 But now have some bugs with switch buttons & angles (dialog/backgrround  widget)
![image](https://user-images.githubusercontent.com/8083855/72219104-a8e38300-355b-11ea-909a-81689bc19d6d.png)
it's strange, but background have problem only with latte and i don't know why...
I like rounded buttons - it's looking very fresh, but this spoiled on switch-buttons.
It's not final version. I think how doing this better
https://github.com/varlesh/rounded

**Comment by psifidotos** [comment]
looks nice!!! :)

> it's strange, but background have problem only with latte and i don't know why...

can you explain me with a screenshot in what way? it could be Latte fault...

**Comment by varlesh** [comment]
shadows superimposed on angles
![image](https://user-images.githubusercontent.com/8083855/72220848-91fa5c00-356e-11ea-9a11-d875291f9074.png)

**Comment by psifidotos** [comment]
> shadows superimposed on angles
> ![image](https://user-images.githubusercontent.com/8083855/72220848-91fa5c00-356e-11ea-9a11-d875291f9074.png)

dont bother with it, it is Latte fault https://bugs.kde.org/show_bug.cgi?id=416175 but I will need to track it down and see what breaks and why... there is an easy workaround but I would prefer to search first why this is happening...

https://bugs.kde.org/show_bug.cgi?id=416175

**Comment by psifidotos** [comment]
@varlesh all fine, I fixed the shadow issue with Latte both for upcoming Latte 0.9.8 and master versions

**Comment by varlesh** [comment]
@psifidotos fine.
i'm replace rounded buttons to more squared, because i can't fix little size buttons (<20px)
But now it's looking good:
![image](https://user-images.githubusercontent.com/8083855/72234052-76319d00-35e4-11ea-9bc5-43bb147bf941.png)

**Comment by varlesh** [comment]
@psifidotos i found another bug. If used inverted scheme for backgrond on latte - widgets on latted have white overlay color:
![image](https://user-images.githubusercontent.com/8083855/72342476-effd7f80-36e5-11ea-9a14-943278a4ad90.png)

**Comment by varlesh** [comment]
@psifidotos how unfasten latte form bottom screen? (it's present on your screenshot https://github.com/PapirusDevelopmentTeam/materia-kde/issues/71#issuecomment-569453871).

**Comment by trmdi** [comment]
> @psifidotos how unfasten latte form bottom screen? (it's present on your screenshot [#71 (comment)](https://github.com/PapirusDevelopmentTeam/materia-kde/issues/71#issuecomment-569453871)).

Floating dock, it's available in the git version currently.

**Comment by psifidotos** [comment]
> @psifidotos i found another bug. If used inverted scheme for background on latte - widgets on latte have white overlay color:
> ![image](https://user-images.githubusercontent.com/8083855/72342476-effd7f80-36e5-11ea-9a14-943278a4ad90.png)
 
you can disable auto-coloring for these applets. Right click Dock -> Dock Settings -> Rearrange and configurure your applets -> hover any of these applets and from its tooltip, click the "drop" icon

**Comment by varlesh** [comment]
@trmdi strange... i'm try latest git-version form Neon unstable repo and Floating options not active:
![image](https://user-images.githubusercontent.com/8083855/72615474-348b5400-394e-11ea-8f7a-084d9d37f8ba.png)
You know why this not actived and how enable it?

**Comment by varlesh** [comment]
@psifidotos I think soon release theme on kde store:
![image](https://user-images.githubusercontent.com/8083855/72615816-f6dafb00-394e-11ea-9544-718d2f2582b8.png)

**Comment by varlesh** [comment]
added:
https://store.kde.org//p/1352754/

**Comment by psifidotos** [comment]
@varlesh thank you !! Really great release!! I will follow your updates...

1. Make sure to use latest master version because it contains a fix for panel background. It prevents panel shadows to overlap at all cases even when background size is set to 0%.

2. For Floating options to become enabled you need to make one of your panels floating... Appearance -> Margins -> Thickness -> Screen [_increase that slider in order to make your Latte docks/panels to float_]

**Comment by varlesh** [comment]
@psifidotos 
1. yes, all fine

2. worked perfect!!!

![Screenshot_20200117_205546-1](https://user-images.githubusercontent.com/8083855/72630752-73c89d80-396c-11ea-9de5-03426498ed82.png)

**Comment by varlesh** [comment]
@psifidotos i'm now have some bug with notifications.
![Screenshot_20200117_210734](https://user-images.githubusercontent.com/8083855/72631391-9effbc80-396d-11ea-9652-d39f8f8aa153.png)
on completed notifications used STRECHED vertical line... it's spoil style, because on theme used very specific line - ascending and descending.

**Comment by varlesh** [comment]
this style used for more elements:
slider (background), searchbar and etc:
![image](https://user-images.githubusercontent.com/8083855/72631744-3cf38700-396e-11ea-8a9c-a223cdc4c8c7.png)
![image](https://user-images.githubusercontent.com/8083855/72631819-61e7fa00-396e-11ea-8248-b414ef123a8b.png)

**Comment by psifidotos** [comment]
1. It could be a notifications interface bug, you can try to report it to plasma devs

2. For elements that break why not use the same elements from your other plasma themes with just correct colors?

**Comment by varlesh** [comment]
on code used this:
```
Component {
                    id: notificationDelegate
                    ColumnLayout {
                        spacing: units.smallSpacing

                        RowLayout {
                            Item {
                                id: groupLineContainer
                                Layout.fillHeight: true
                                Layout.topMargin: units.smallSpacing
                                width: units.iconSizes.small
                                visible: model.isInGroup

                                PlasmaCore.SvgItem {
                                    elementId: "vertical-line"
                                    svg: lineSvg
                                    anchors.horizontalCenter: parent.horizontalCenter
                                    width: units.iconSizes.small
                                    height: parent.height
                                }
                            }
```
`width: units.iconSizes.small` - it's strange value for vertical line.

**Comment by varlesh** [comment]
reported: https://bugs.kde.org/show_bug.cgi?id=416386
