### ISSUE TITLE
Fix some accessibility issues

### ISSUE THREAD

**Issue by federa7675** [PapirusDevelopmentTeam/materia-kde#76]
1. There are some accessibility issue with combo-boxes and general text fields in this theme that make it hard for me to recognize them in various contexts. Here are some detailed explanation with screenshots 

Current Design | Desired Look | Upstream GTK
------------ | ------------- | -------------
![image](https://user-images.githubusercontent.com/64138927/80817173-9a3bdd00-8bd9-11ea-9787-b11548bab2fc.png) | ![image](https://user-images.githubusercontent.com/64138927/80817956-0834d400-8bdb-11ea-9aee-caf6d38ac91d.png) | ![image](https://user-images.githubusercontent.com/64138927/80818262-84c7b280-8bdb-11ea-8482-f5b880215a86.png)

2. When having multiple tabs open e.g. (in kate text editor) the buttons used to navigate the tabs is bigger that it should (broken)

Current Design | Desired Look | Upstream GTK
------------ | ------------- | -------------
![image](https://user-images.githubusercontent.com/64138927/80819197-31566400-8bdd-11ea-9309-4707eb12079e.png) | ![image](https://user-images.githubusercontent.com/64138927/80820859-58fafb80-8be0-11ea-9dfb-f4dc0eeaf22c.png) | ![image](https://user-images.githubusercontent.com/64138927/80820974-8f387b00-8be0-11ea-9581-97b659c07563.png)

**Comment by federa7675** [comment]
@varlesh

**Comment by varlesh** [comment]
> This version compatibility with only Materia GTK 20190315. Please not open issue abot newest upstream color changes, because we don't like new colors.

About big arrows for tabs - i know about this. This hack-method for big close button. 

![image](https://user-images.githubusercontent.com/8083855/81274700-b1f3e500-9061-11ea-858d-69f75ce13d40.png)


You can change it on Kvantum config, if needed:
```
[Tab]
indicator.size=22
```

**Comment by federa7675** [comment]
> This version compatibility with only Materia GTK 20190315. Please not open issue abot newest upstream color changes, because we don't like new colors.

does this mean this mean the text field input design won't change ?

**Comment by varlesh** [comment]
Now no, maybe on future

**Comment by federa7675** [comment]
Thanks :)

**Comment by M86xKC** [comment]
@varlesh thanks for implementing these features :)

can you please some more padding to combo box

![Screenshot](https://user-images.githubusercontent.com/31791780/82742604-fcf34500-9d4f-11ea-8957-3959fefd6989.png)

**Comment by varlesh** [comment]
@M86xKC It's only preview. I think padding decrease in useful space

**Comment by M86xKC** [comment]
@varlesh it does not increase for me when using it with other apps

![Screenshot](https://user-images.githubusercontent.com/31791780/82751255-82551480-9da5-11ea-9dae-8b69ff507ba2.png)

**Comment by varlesh** [comment]
updated

**Comment by M86xKC** [comment]
@varlesh it actually decreased the padding 😄️


Yesterday Build | Today Build
----------|----------
![](https://user-images.githubusercontent.com/31791780/82742604-fcf34500-9d4f-11ea-8957-3959fefd6989.png)|![Screenshot_20200524_192259_Kvantum Preview](https://user-images.githubusercontent.com/31791780/82759168-21e0ca00-9ddb-11ea-8ca4-fac474402b85.png)

**Comment by varlesh** [comment]
no
before:
![1prev2](https://user-images.githubusercontent.com/8083855/82759540-2f0fb000-9dff-11ea-8f91-1898dec83a97.png)
after:
![1prev](https://user-images.githubusercontent.com/8083855/82759542-33d46400-9dff-11ea-92d7-199090e7860e.png)

**Comment by varlesh** [comment]
Kvantum
before
![Screenshot_20200524_204754](https://user-images.githubusercontent.com/8083855/82759670-eb697600-9dff-11ea-977d-96c48c74b329.png)
after
![Screenshot_20200524_204725](https://user-images.githubusercontent.com/8083855/82759679-f3c1b100-9dff-11ea-891d-4a0d300322c9.png)

**Comment by M86xKC** [comment]
This is fine now for some reason 😅️ Thanks

**Comment by M86xKC** [comment]
@varlesh Today suddenly this happened!

![Kvantum Preview](https://user-images.githubusercontent.com/31791780/83172279-e447ae00-a106-11ea-9bf5-f74f6d41a766.png)

**Comment by varlesh** [comment]
I didn't do anything

**Comment by M86xKC** [comment]
Dolphin Group Toolbar Buttons: selected buttons appear to be broken

![Dolphin Group Toolbar Buttons](https://user-images.githubusercontent.com/31791780/83174605-29b9aa80-a10a-11ea-9f57-2f39644b5a1a.png)

**Comment by varlesh** [comment]
Group Toolbar Vuttons not supported, because it's not Materia's style

**Comment by M86xKC** [comment]
what tools do you use to optimize/minify SVG for Kvantum, unfortunatly inkscape exports have a lot of bloat

**Comment by varlesh** [comment]
svgo

**Comment by M86xKC** [comment]
Thanks :)

**Comment by M86xKC** [comment]
> Group Toolbar Buttons not supported, because it's not Materia's style

You're right but even if I disable Group Toolbar Buttons the highlight light under the icon is too close to the icons IMO

![Screenshot of Group Toolbar Buttons disabled](https://user-images.githubusercontent.com/31791780/83178539-2aedd600-a110-11ea-8050-a9e682a832cf.png)

**Comment by varlesh** [comment]
You right i fix that
