### ISSUE TITLE
Kde connect sms text color

### ISSUE THREAD

**Issue by vince93290** [PapirusDevelopmentTeam/materia-kde#78]
hello first I would like to say that the theme is beautiful.

I found a problem with the text color in kde connect, the correspondents' messages are dark gray on a dark blue background which makes the text difficult to read.

Would it be possible to make the text clearer?

![kde connect materia](https://user-images.githubusercontent.com/44445302/81928951-65bb1e80-95e6-11ea-9cc5-947b6658dd97.png)

**Comment by varlesh** [comment]
kirigami

**Comment by varlesh** [comment]
New apps migrate/use to Kirigami, it's  Qt Quick Controls framework. And can change only colors. Other ALL elements hardcoded. It's good for mobile platforms, but stuppid for desktop...
I think, KDE now died as Qt DESKTOP and kill customization... now it's mobile desktop, with only Breeze style(((
More info abot that sayd @tsujan:
https://www.reddit.com/r/kde/comments/9p8uwm/open_a_friendly_and_constructive_discussion_about/

https://github.com/lxqt/lxqt/issues/1433

**Comment by tsujan** [comment]
> I think, KDE now died as Qt DESKTOP and kill customization.

IMHO, it's too soon for that conclusion ;) But, unfortunately, they're going in that direction, whether they know it or not -- as Gnome did intentionally. Another similarity with Gnome is that they may accuse people of "unfriendliness" (Gnome devs use the word "impoliteness") if people say the obvious: THIS IS A DESKTOP ENVIRONMENT, NOT A MOBILE PHONE.

**Comment by trmdi** [comment]
Oh, I've just found a way to override KDE's Qt Quick Control style from this link: https://doc.qt.io/archives/qt-5.11/qtquickcontrols2-customize.html

Here is a demo, you can try it:
1, Extract this file: [org.kde.zip](https://github.com/PapirusDevelopmentTeam/materia-kde/files/4636221/org.kde.zip)
2, Run:
```bash
$ QT_QUICK_CONTROLS_STYLE_PATH=/path/to/parent-of-org.kde.desktop plasmawindowed org.kde.plasma.digitalclock
```
3, Open the configuration window of that applet
4, The result is that I can override KDE's Button.qml with my own file.

**Comment by trmdi** [comment]
With KvMojave dark, the text still looks ok, so this is likely a bug in Materia.

**Comment by trmdi** [comment]
In fact it uses the base and highlight color in this case, so a workaround is that you can clone the Kvantum theme then edit the color, and use that new theme for kdeconnect-sms

**Comment by tsujan** [comment]
> With KvMojave dark, the text still looks ok

I think that's by chance.

> In fact it uses the base and highlight color in this case

If so, the app has a problem that should be fixed by its developers. Any workaround would be a waste of time, IMO.

**Comment by trmdi** [comment]
Then could you @vince93290 report the bug to KDE Connect's dev on KDE Bug Tracker?

**Comment by varlesh** [comment]
bug is called qml

Now set KvMojave and Breeze Light Color scheme and admire perfect result
![image](https://user-images.githubusercontent.com/8083855/82110733-a08d9580-9751-11ea-9961-137985c18de8.png)

**Comment by varlesh** [comment]
Yes, it's unlogic action. But now you see how kirigami app draw widgets, how and from apply colors ...

**Comment by tsujan** [comment]
I'm working in LXQt and can't log into KDE for now. @varlesh @trmdi Are you sure that the app in question doesn't use KDE color scheme directly? Some apps do, especially QML ones. What happens when you change the KDE color scheme, not the theme?

**Comment by varlesh** [comment]
@tsujan for messages box used colors from kvantum theme (base.color highlight.color & text.color):
https://github.com/KDE/kdeconnect-kde/blob/master/smsapp/qml/ChatMessage.qml#L214
other elements used from system color scheme or from plasma

**Comment by varlesh** [comment]
It's not bug only SMS module KDEConnect. Other modules draw not better:
![image](https://user-images.githubusercontent.com/8083855/82111120-c61b9e80-9753-11ea-8c3b-d454aacdb716.png)

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/82111135-e6e3f400-9753-11ea-8881-bc4326775a78.png)

**Comment by tsujan** [comment]
@varlesh Then, no workaround is possible. It's a mess. Reporting would have no result. These are among those cases, where KDE started to behave like Gnome...

This isn't Qt; this isn't QML either. It's a mixture KDE developers have created (→ qqc2-desktop-style). I told them it's wrong but they don't listen.

**Comment by varlesh** [comment]
Yes, it's mix = plasma widgets + engine widgets + colors from plasma theme + colors from system color scheme

**Comment by varlesh** [comment]
@tsujan How you said earlier, Breeze it's engine for hide this bugs and errors

**Comment by tsujan** [comment]
Yes, Breeze is made to hide problems. It ignores so many `QStyle` parameters to do so. Other parts of KDE do too but `qqc2-desktop-style` is the worst: it tries to mimic QStyle for QML apps. That's the cause of all problems.

Qt allows QML apps to be styled *in their own way*. Enforcing `QStyle` on QML apps is a funny mistake.
