### ISSUE TITLE
Link to KDE:Extra repo for openSUSE

### ISSUE THREAD

**Issue by baudm** [PapirusDevelopmentTeam/materia-kde#79]
The semi-official KDE:Extra repo also packages materia-kde.

Download link: https://software.opensuse.org/download/package?package=materia-kde&project=KDE%3AExtra
OBS link: https://build.opensuse.org/package/show/KDE:Extra/materia-kde

**Comment by SmartFinn** [comment]
The repo uses the [same package](https://build.opensuse.org/request/show/808566) that already in the list. I won't add the duplicate. But thanks for the suggestion, I will following this repository.
