### ISSUE TITLE
Wrong window title colors in dark mode

### ISSUE THREAD

**Issue by congard** [PapirusDevelopmentTeam/materia-kde#81]
Recently I noticed that the colors of the window title and the bottom panel in Dolphin don't match. This is only on a dark theme. On the light everything ok

![Screenshot_20200612_163837](https://user-images.githubusercontent.com/35779485/84508669-530e3500-accb-11ea-9f87-327dc86d8ee2.png)
![Screenshot_20200612_163931](https://user-images.githubusercontent.com/35779485/84508684-586b7f80-accb-11ea-999a-5ab55d2ab720.png)

How it can be fixed?

I'm using ArchLinux, package materia-kde 20200523-1 and kvantum-theme-materia 20200523-1

**Comment by varlesh** [comment]
You use old decoration or cache not updated:
https://github.com/PapirusDevelopmentTeam/materia-kde/commit/76c148ac91be3c593901bb001195c6b8e01f4a6e#diff-40f585904a456c51c54a77946e255e97
