### ISSUE TITLE
[GNOME] Titlebar color in Materia doesn't match with the menu and toolbar color.

### ISSUE THREAD

**Issue by afraidofmusic** [PapirusDevelopmentTeam/materia-kde#83]
I am using the Materia GTK built from the repository and Kvantum Materia theme from the script in this repository.

When using Materia GTK theme and Materia Kvantum theme, the colors don't match.
![Screenshot from 2020-06-25 14-19-18](https://user-images.githubusercontent.com/25895258/85711219-9195ed80-b6d6-11ea-9682-e259edbe0e9c.png)

When using the Materia GTK theme and Materia-Dark Kvantum theme, the colors do match.
![Screenshot from 2020-06-25 14-19-43](https://user-images.githubusercontent.com/25895258/85711315-aecabc00-b6d6-11ea-8f40-deae9d8f7067.png)

**Comment by varlesh** [comment]
It's not critical, because need recolor & create another aurorae theme for Materia only. But now it's compability with Materia Dark

**Comment by varlesh** [comment]
changed only background color, because impossible change colors for icons on Toolbar - it's draw Qt
