### ISSUE TITLE
Spectacle (screenshot) broken with area selection - Materia Dark

### ISSUE THREAD

**Issue by codic12** [PapirusDevelopmentTeam/materia-kde#85]
All the information text and the resolution text is a light grey on white, instead of a black on white (or better, white on black). try it and see

**Comment by varlesh** [comment]
See, on sources used color for text `.windowText`. This can be themable.
https://github.com/KDE/spectacle/blob/master/src/QuickEditor/QuickEditor.cpp#L67
BUT for background used single style. This can not be themable.
https://github.com/KDE/spectacle/blob/master/src/QuickEditor/QuickEditor.cpp#L61-L65
I'm not understand why they not use `.window.color` for background color...

**Comment by varlesh** [comment]
fixed
