### ISSUE TITLE
User icon doesnt fit in Application launcher

### ISSUE THREAD

**Issue by a8underscore** [PapirusDevelopmentTeam/materia-kde#88]
![image](https://user-images.githubusercontent.com/60801647/89207309-61602b00-d56f-11ea-85ec-05fe195d1f6b.png)
Operating System: openSUSE Tumbleweed 20200801
KDE Plasma Version: 5.19.4
KDE Frameworks Version: 5.72.0
Qt Version: 5.15.0
Kernel Version: 5.7.11-1-default
OS Type: 64-bit
Processors: 4 × Intel® Core™ i7-5650U CPU @ 2.20GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 6000

**Comment by varlesh** [comment]
It's strange but with default user logo i'm not seen this circle:
![image](https://user-images.githubusercontent.com/8083855/89250118-156fbd80-d625-11ea-8b4f-e7dcf349ed8a.png)

**Comment by varlesh** [comment]
Plasma 5.19.4

**Comment by a8underscore** [comment]
odd.
the profile photo i had was not set. after i set it the profile photo is still rounded but fits fine, it did this in breeze too, could it be a setting of some kind?

![image](https://user-images.githubusercontent.com/60801647/89250868-8fbf2400-d5ca-11ea-8cee-1f55ea3d523e.png)

**Comment by a8underscore** [comment]
![issue](https://user-images.githubusercontent.com/60801647/89251463-e8db8780-d5cb-11ea-8aa6-68b3fb753835.gif)
it seems this issue is something else. as i cant set profile photo to default.
