### ISSUE TITLE
Disable app pin thing when there is only one virtral desktop

### ISSUE THREAD

**Issue by a8underscore** [PapirusDevelopmentTeam/materia-kde#89]
Breeze does this, how do i get materia to do this too?
![image](https://user-images.githubusercontent.com/60801647/89214000-d7b65a80-d57a-11ea-8c03-d2d8f818948f.png)

**Comment by varlesh** [comment]
How reproduce this?

**Comment by a8underscore** [comment]
remove all virtual desktops, that is only step
![image](https://user-images.githubusercontent.com/60801647/89251181-3d323780-d5cb-11ea-8f4b-9d02ac596cc0.png)

this button allows you to keep window open even when switching virtual desktop.

on breeze dark it leaves screen.
![image](https://user-images.githubusercontent.com/60801647/89251242-5fc45080-d5cb-11ea-8363-20087d61b553.png)

on materia it stay 
![image](https://user-images.githubusercontent.com/60801647/89251328-913d1c00-d5cb-11ea-9549-f5d84fbadac8.png)

**Comment by varlesh** [comment]
I'm not understand you.
> the button that has red error in issue report allows you to keep window open even when switching virtual desktop.
you mean `kdialog --error ERROR`
After this appears this dot on tasks?
![image](https://user-images.githubusercontent.com/8083855/89276171-5f23cc80-d654-11ea-99a6-3fae81432766.png) - it's Tasks (Icons only) Widget?

**Comment by a8underscore** [comment]
sorry, 
i made a typo. I meant "The button that has red **arrow** " there is no error.
im saying it shouldn't show when there is only one desktop as it has no use. it doesn't show in Breeze theme.

**Comment by varlesh** [comment]
For workspace switcher used `pager` widget. But i can't find this dot on widgets directory.
Also i'm testing with one virtual desktop and not seen workspace or dot...
You can record video or gif? I'm really want help you, but can't reproduce this

**Comment by a8underscore** [comment]
https://streamable.com/rzjgqu
here is video i recorded
as u can see when there is one desktop on breeze the dot/pin goes away. on materia it stays.

i hope video helps. thanks again

**Comment by varlesh** [comment]
Ouh it's aurorae))) Breeze it's another engine decoration and very different with aurorae.
Aurorae very old engine and option hide/appeared `alldesktops` button must be writen on kwin code. 
From [doc](https://github.com/KDE/kwin/blob/master/plugins/kdecorations/aurorae/theme-description):
>Each button can have different states. So a button could be hovered, pressed, deactivated and you
might want to provide different styles for active and inactive windows. You can use the following
element prefix to provide styles for the buttons:
 * active (normal button for active window)
 * inactive (normal button for inactive window)
 * hover (hover state for active window)
 * hover-inactive (hover state for inactive window)
 * pressed (button is pressed)
 * pressed-inactive (pressed inactive button)
 * deactivated (button cannot be clicked, e.g. window cannot be closed)
 * deactivated-inactive (same for inactive windows)

Sorry, i can't doing anything. We not have `empty` state on button or other solution for this.
Open request on KDE...
