### ISSUE TITLE
Upstream color changes

### ISSUE THREAD

**Issue by ubluish** [PapirusDevelopmentTeam/materia-kde#9]
![screenshot_20180519_183525](https://user-images.githubusercontent.com/21042432/40270781-95597cfc-5b93-11e8-81fd-38b596372a57.png)

**Comment by archqob** [comment]
@varlesh

**Comment by varlesh** [comment]
@dooqob updated... but without yakuake skin for now

**Comment by varlesh** [comment]
when will be completed, i'm publish new release.
Also your PR not full, but thx for suggestion :) changed other colors too
![image](https://user-images.githubusercontent.com/8083855/42408301-95277f72-81db-11e8-8a8b-beedb5fb3afb.png)

**Comment by dooqob** [comment]
@varlesh Thanks alot :D

**Comment by Warmuser** [comment]
I can't find the GTK theme on the KDE store. :(

**Comment by varlesh** [comment]
https://github.com/nana-4/materia-theme#packages

**Comment by Warmuser** [comment]
Thanks

**Comment by Warmuser** [comment]
I got other versions of materia gtk but after the installation with the suggested steps, I can't notice differences. The tab colors doesn't match the color of the qt theme style. wtf

**Comment by ubluish** [comment]
@varlesh Problem still exist with titlebar and menubar both have different colors
![1](https://user-images.githubusercontent.com/21042432/68523564-b4000580-02c3-11ea-94be-d4d95baf8ef3.png)

**Comment by varlesh** [comment]
New version colors:
![image](https://user-images.githubusercontent.com/8083855/68525289-8463f400-02e9-11ea-993d-e3d1ee430ae8.png)

**Comment by varlesh** [comment]
GTK2 not worked for me:
![image](https://user-images.githubusercontent.com/8083855/68525386-62b73c80-02ea-11ea-9ade-a47f58b84c2e.png)

**Comment by varlesh** [comment]
oh, sorry worked from root direcory, but not from  home

**Comment by varlesh** [comment]
They again change all colors, like as Adapta...
It's very sadly!
background colors now more contrast, BUT highlight VERY VERY VERY faded...
I don't know how migrate this change on Papirus with new Materia colors.
See example:
![image](https://user-images.githubusercontent.com/8083855/68525923-fb03f000-02ef-11ea-9355-8cb8e1e28ee5.png)

**Comment by varlesh** [comment]
As solution i can make moded version with Papirus compability. For example, for icons on plasma theme used previous color, but for other elements new (slider, selection, active button and etc)
![image](https://user-images.githubusercontent.com/8083855/68526013-e2480a00-02f0-11ea-9bb9-ea6530df902e.png)
![image](https://user-images.githubusercontent.com/8083855/68526027-fc81e800-02f0-11ea-8a0b-72e12186fb11.png)
BUT we lost unification Highlight color and general style

**Comment by varlesh** [comment]
After careful consideration i decide not update colors for new upstream version.
Reasons:
- I don't like new colors
- We lost compatibility with Papirus
- Very fadded Highlight color
- Mostly distros used old version. You can analize repology for that:
https://repology.org/project/materia-gtk-theme/versions
More popular version **20190315**. Debian Testing used this version too... i think this version will be avaiilable on Ubuntu 20.04 LTS
