### ISSUE TITLE
Window decorations disappear in Wayland

### ISSUE THREAD

**Issue by eeickmeyer** [PapirusDevelopmentTeam/materia-kde#92]
With plasma-wayland on the horizon it would be good to get this fixed. Here's a screenshot of Dolphin in Ubuntu Studio Groovy Gorilla (future 20.10):
![Screenshot_20200905_104453](https://user-images.githubusercontent.com/7434781/92310634-22a20400-ef65-11ea-872e-fcf8cb0a629c.png)

Basically, the window decorations are a complete transparent blur with no buttons at all. I can confirm that Kvantum, colors, and everything else works fine.

**Comment by theGeekyLad** [comment]
It's the same for me too:

![plasma_materia_transparent_titlebars](https://user-images.githubusercontent.com/15625446/103238946-3806c800-4972-11eb-90cf-0ff630860744.png)

**Comment by varlesh** [comment]
Sorry guys, but i can'r run Wayland session & test it. My pc freezed with wayland.
But found bug: https://bugs.kde.org/show_bug.cgi?id=422342

**Comment by varlesh** [comment]
It's worked with Oxygen or other Aurorae themes?

**Comment by varlesh** [comment]
try see logs on konsole:
```
killall -9 kwin_wayland
kwin_wayland
```

**Comment by uranuspucksaxophone** [comment]
I can reproduce this bug in Arch Linux with the lastest version of KDE and the theme.

**Comment by Mikaka27** [comment]
I see the same thing, but I cannot capture logs the way you mentioned, as soon as killall -9 kwin_wayland, the session dies and is restarted (without konsole window).
I'll try to look for errors in journal.

**Comment by varlesh** [comment]
sorry, i don't know. I have NVIDIA

**Comment by Mikaka27** [comment]
I also have nvidia. I will keep looking.

**Comment by gijsrrr** [comment]
This has been resolved in the latest plasma. Could you please close this one @SmartFinn ?
