### ISSUE TITLE
Plasma panel got transparent

### ISSUE THREAD

**Issue by dafeinayius** [PapirusDevelopmentTeam/materia-kde#95]
Operating System: Arch Linux
KDE Plasma Version: 5.20.3
KDE Frameworks Version: 5.76.0
Qt Version: 5.15.1
materia-kde Version: 20201113-1
Choose 'Materia Color' as Plasma Style makes panel and related addons transparent.

**Comment by lucasjome** [comment]
Same here.

**Comment by varlesh** [comment]
fixed
