### ISSUE TITLE
Missing window buttons on firefox

### ISSUE THREAD

**Issue by lyra64** [PapirusDevelopmentTeam/materia-kde#97]
Window buttons on firefox missing with materia kde theme, both light and dark.
Steps to reproduce:
1. Go to Customize in firefox
![image](https://user-images.githubusercontent.com/18562602/100696176-d1c56000-3347-11eb-9996-bcfc29fc5cf4.png)
2. Check "Title Bar"
![image](https://user-images.githubusercontent.com/18562602/100696156-c5d99e00-3347-11eb-85a9-50cb9efa88b0.png)

Here's some screenshots:
Materia Lite:
![image](https://user-images.githubusercontent.com/18562602/100696098-91fe7880-3347-11eb-8e41-38fb1c388852.png)
Materia Dark:
![image](https://user-images.githubusercontent.com/18562602/100696216-e6a1f380-3347-11eb-9c70-38b9eea5434a.png)
Materia:
![image](https://user-images.githubusercontent.com/18562602/100696234-f28db580-3347-11eb-8341-ff85cbc7da3e.png)
Breeze:
![image](https://user-images.githubusercontent.com/18562602/100696286-0e915700-3348-11eb-9dca-f010ba9f7091.png)

**Comment by varlesh** [comment]
If it's draw on Qt, but not rendered for GTK. It's not our bug. Other GTK-apps worked?

**Comment by lyra64** [comment]
Looks like the bug happens in other GTK apps

**Comment by varlesh** [comment]
Anyway i'm not confirm this:
![image](https://user-images.githubusercontent.com/8083855/100697043-65317c00-33ae-11eb-9c88-63e3e71bfd07.png)
GTK-apps it's not our bugs. This pack for only Qt-apps.
Check settings on SystemSetting for GTK or open issue on Materia-GTK
